// 220+ well-known global brands with Clearbit logo URLs
export const LOGOS = [

  // ── Technology ──────────────────────────────────────────────────────────
  { name: 'Apple',         logo: 'https://logo.clearbit.com/apple.com',           category: 'tech' },
  { name: 'Google',        logo: 'https://logo.clearbit.com/google.com',          category: 'tech' },
  { name: 'Microsoft',     logo: 'https://logo.clearbit.com/microsoft.com',       category: 'tech' },
  { name: 'Samsung',       logo: 'https://logo.clearbit.com/samsung.com',         category: 'tech' },
  { name: 'Amazon',        logo: 'https://logo.clearbit.com/amazon.com',          category: 'tech' },
  { name: 'Meta',          logo: 'https://logo.clearbit.com/meta.com',            category: 'tech', aliases: ['facebook'] },
  { name: 'Netflix',       logo: 'https://logo.clearbit.com/netflix.com',         category: 'tech' },
  { name: 'Spotify',       logo: 'https://logo.clearbit.com/spotify.com',         category: 'tech' },
  { name: 'Uber',          logo: 'https://logo.clearbit.com/uber.com',            category: 'tech' },
  { name: 'Airbnb',        logo: 'https://logo.clearbit.com/airbnb.com',          category: 'tech' },
  { name: 'PayPal',        logo: 'https://logo.clearbit.com/paypal.com',          category: 'tech' },
  { name: 'YouTube',       logo: 'https://logo.clearbit.com/youtube.com',         category: 'tech', aliases: ['yt'] },
  { name: 'Instagram',     logo: 'https://logo.clearbit.com/instagram.com',       category: 'tech', aliases: ['insta'] },
  { name: 'Twitter',       logo: 'https://logo.clearbit.com/twitter.com',         category: 'tech', aliases: ['x'] },
  { name: 'LinkedIn',      logo: 'https://logo.clearbit.com/linkedin.com',        category: 'tech' },
  { name: 'Adobe',         logo: 'https://logo.clearbit.com/adobe.com',           category: 'tech' },
  { name: 'Intel',         logo: 'https://logo.clearbit.com/intel.com',           category: 'tech' },
  { name: 'Nvidia',        logo: 'https://logo.clearbit.com/nvidia.com',          category: 'tech' },
  { name: 'Tesla',         logo: 'https://logo.clearbit.com/tesla.com',           category: 'tech' },
  { name: 'Dell',          logo: 'https://logo.clearbit.com/dell.com',            category: 'tech' },
  { name: 'HP',            logo: 'https://logo.clearbit.com/hp.com',              category: 'tech' },
  { name: 'IBM',           logo: 'https://logo.clearbit.com/ibm.com',             category: 'tech' },
  { name: 'Oracle',        logo: 'https://logo.clearbit.com/oracle.com',          category: 'tech' },
  { name: 'Cisco',         logo: 'https://logo.clearbit.com/cisco.com',           category: 'tech' },
  { name: 'Zoom',          logo: 'https://logo.clearbit.com/zoom.us',             category: 'tech' },
  { name: 'Slack',         logo: 'https://logo.clearbit.com/slack.com',           category: 'tech' },
  { name: 'Dropbox',       logo: 'https://logo.clearbit.com/dropbox.com',         category: 'tech' },
  { name: 'Reddit',        logo: 'https://logo.clearbit.com/reddit.com',          category: 'tech' },
  { name: 'TikTok',        logo: 'https://logo.clearbit.com/tiktok.com',          category: 'tech' },
  { name: 'Snapchat',      logo: 'https://logo.clearbit.com/snapchat.com',        category: 'tech' },
  { name: 'Pinterest',     logo: 'https://logo.clearbit.com/pinterest.com',       category: 'tech' },
  { name: 'Discord',       logo: 'https://logo.clearbit.com/discord.com',         category: 'tech' },
  { name: 'Twitch',        logo: 'https://logo.clearbit.com/twitch.tv',           category: 'tech' },
  { name: 'eBay',          logo: 'https://logo.clearbit.com/ebay.com',            category: 'tech' },
  { name: 'Shopify',       logo: 'https://logo.clearbit.com/shopify.com',         category: 'tech' },
  { name: 'Stripe',        logo: 'https://logo.clearbit.com/stripe.com',          category: 'tech' },
  { name: 'WhatsApp',      logo: 'https://logo.clearbit.com/whatsapp.com',        category: 'tech' },
  { name: 'Telegram',      logo: 'https://logo.clearbit.com/telegram.org',        category: 'tech' },
  { name: 'GitHub',        logo: 'https://logo.clearbit.com/github.com',          category: 'tech' },
  { name: 'Figma',         logo: 'https://logo.clearbit.com/figma.com',           category: 'tech' },
  { name: 'Notion',        logo: 'https://logo.clearbit.com/notion.so',           category: 'tech' },
  { name: 'Canva',         logo: 'https://logo.clearbit.com/canva.com',           category: 'tech' },
  { name: 'Lyft',          logo: 'https://logo.clearbit.com/lyft.com',            category: 'tech' },
  { name: 'Coinbase',      logo: 'https://logo.clearbit.com/coinbase.com',        category: 'tech' },
  { name: 'Robinhood',     logo: 'https://logo.clearbit.com/robinhood.com',       category: 'tech' },

  // ── Food & Beverage ─────────────────────────────────────────────────────
  { name: "McDonald's",    logo: 'https://logo.clearbit.com/mcdonalds.com',       category: 'food', aliases: ['mcdonalds', 'mcdonald'] },
  { name: 'Coca-Cola',     logo: 'https://logo.clearbit.com/coca-cola.com',       category: 'food', aliases: ['coke', 'cocacola', 'coca cola'] },
  { name: 'Pepsi',         logo: 'https://logo.clearbit.com/pepsi.com',           category: 'food' },
  { name: 'Starbucks',     logo: 'https://logo.clearbit.com/starbucks.com',       category: 'food' },
  { name: 'KFC',           logo: 'https://logo.clearbit.com/kfc.com',             category: 'food' },
  { name: 'Subway',        logo: 'https://logo.clearbit.com/subway.com',          category: 'food' },
  { name: 'Pizza Hut',     logo: 'https://logo.clearbit.com/pizzahut.com',        category: 'food', aliases: ['pizzahut'] },
  { name: "Domino's",      logo: 'https://logo.clearbit.com/dominos.com',         category: 'food', aliases: ['dominos', 'domino'] },
  { name: 'Burger King',   logo: 'https://logo.clearbit.com/burgerking.com',      category: 'food', aliases: ['burgerking', 'bk'] },
  { name: 'Heineken',      logo: 'https://logo.clearbit.com/heineken.com',        category: 'food' },
  { name: 'Red Bull',      logo: 'https://logo.clearbit.com/redbull.com',         category: 'food', aliases: ['redbull'] },
  { name: 'Monster',       logo: 'https://logo.clearbit.com/monsterenergy.com',   category: 'food' },
  { name: 'Nescafe',       logo: 'https://logo.clearbit.com/nescafe.com',         category: 'food' },
  { name: 'Nutella',       logo: 'https://logo.clearbit.com/nutella.com',         category: 'food' },
  { name: 'Heinz',         logo: 'https://logo.clearbit.com/heinz.com',           category: 'food' },
  { name: "Kellogg's",     logo: 'https://logo.clearbit.com/kelloggs.com',        category: 'food', aliases: ['kelloggs', 'kellogs'] },
  { name: 'Nestlé',        logo: 'https://logo.clearbit.com/nestle.com',          category: 'food', aliases: ['nestle'] },
  { name: 'Pringles',      logo: 'https://logo.clearbit.com/pringles.com',        category: 'food' },
  { name: "Lay's",         logo: 'https://logo.clearbit.com/lays.com',            category: 'food', aliases: ['lays'] },
  { name: 'Oreo',          logo: 'https://logo.clearbit.com/oreo.com',            category: 'food' },
  { name: 'Tabasco',       logo: 'https://logo.clearbit.com/tabasco.com',         category: 'food' },
  { name: 'Budweiser',     logo: 'https://logo.clearbit.com/budweiser.com',       category: 'food' },
  { name: 'Corona',        logo: 'https://logo.clearbit.com/corona.com',          category: 'food' },
  { name: "Dunkin'",       logo: 'https://logo.clearbit.com/dunkindonuts.com',    category: 'food', aliases: ['dunkin', 'dunkindonuts'] },
  { name: 'Chipotle',      logo: 'https://logo.clearbit.com/chipotle.com',        category: 'food' },
  { name: 'Shake Shack',   logo: 'https://logo.clearbit.com/shakeshack.com',      category: 'food', aliases: ['shakeshack'] },
  { name: 'Tim Hortons',   logo: 'https://logo.clearbit.com/timhortons.com',      category: 'food', aliases: ['timhortons'] },
  { name: 'Five Guys',     logo: 'https://logo.clearbit.com/fiveguys.com',        category: 'food', aliases: ['fiveguys'] },
  { name: 'Absolut',       logo: 'https://logo.clearbit.com/absolut.com',         category: 'food' },
  { name: 'Bacardi',       logo: 'https://logo.clearbit.com/bacardi.com',         category: 'food' },

  // ── Fashion & Luxury ────────────────────────────────────────────────────
  { name: 'Nike',           logo: 'https://logo.clearbit.com/nike.com',           category: 'fashion' },
  { name: 'Adidas',         logo: 'https://logo.clearbit.com/adidas.com',         category: 'fashion' },
  { name: 'Gucci',          logo: 'https://logo.clearbit.com/gucci.com',          category: 'fashion' },
  { name: 'Louis Vuitton',  logo: 'https://logo.clearbit.com/louisvuitton.com',   category: 'fashion', aliases: ['lv', 'louisvuitton'] },
  { name: 'Zara',           logo: 'https://logo.clearbit.com/zara.com',           category: 'fashion' },
  { name: 'H&M',            logo: 'https://logo.clearbit.com/hm.com',             category: 'fashion', aliases: ['hm', 'handm'] },
  { name: 'Prada',          logo: 'https://logo.clearbit.com/prada.com',          category: 'fashion' },
  { name: 'Versace',        logo: 'https://logo.clearbit.com/versace.com',        category: 'fashion' },
  { name: 'Burberry',       logo: 'https://logo.clearbit.com/burberry.com',       category: 'fashion' },
  { name: 'Ralph Lauren',   logo: 'https://logo.clearbit.com/ralphlauren.com',    category: 'fashion', aliases: ['ralphlauren', 'polo'] },
  { name: 'Tommy Hilfiger', logo: 'https://logo.clearbit.com/tommy.com',          category: 'fashion', aliases: ['tommy', 'tommyhilfiger'] },
  { name: 'Calvin Klein',   logo: 'https://logo.clearbit.com/calvinklein.com',    category: 'fashion', aliases: ['ck', 'calvinklein'] },
  { name: "Levi's",         logo: 'https://logo.clearbit.com/levi.com',           category: 'fashion', aliases: ['levis', 'levi'] },
  { name: 'New Balance',    logo: 'https://logo.clearbit.com/newbalance.com',     category: 'fashion', aliases: ['newbalance', 'nb'] },
  { name: 'Puma',           logo: 'https://logo.clearbit.com/puma.com',           category: 'fashion' },
  { name: 'Reebok',         logo: 'https://logo.clearbit.com/reebok.com',         category: 'fashion' },
  { name: 'Under Armour',   logo: 'https://logo.clearbit.com/underarmour.com',    category: 'fashion', aliases: ['ua', 'underarmour'] },
  { name: 'Rolex',          logo: 'https://logo.clearbit.com/rolex.com',          category: 'fashion' },
  { name: 'Chanel',         logo: 'https://logo.clearbit.com/chanel.com',         category: 'fashion' },
  { name: 'Hermès',         logo: 'https://logo.clearbit.com/hermes.com',         category: 'fashion', aliases: ['hermes'] },
  { name: 'Dior',           logo: 'https://logo.clearbit.com/dior.com',           category: 'fashion' },
  { name: 'Balenciaga',     logo: 'https://logo.clearbit.com/balenciaga.com',     category: 'fashion' },
  { name: 'Supreme',        logo: 'https://logo.clearbit.com/supremenewyork.com', category: 'fashion' },
  { name: 'Vans',           logo: 'https://logo.clearbit.com/vans.com',           category: 'fashion' },
  { name: 'Converse',       logo: 'https://logo.clearbit.com/converse.com',       category: 'fashion' },
  { name: 'Timberland',     logo: 'https://logo.clearbit.com/timberland.com',     category: 'fashion' },
  { name: 'The North Face', logo: 'https://logo.clearbit.com/thenorthface.com',   category: 'fashion', aliases: ['northface', 'tnf', 'north face'] },
  { name: 'Patagonia',      logo: 'https://logo.clearbit.com/patagonia.com',      category: 'fashion' },
  { name: 'Fendi',          logo: 'https://logo.clearbit.com/fendi.com',          category: 'fashion' },
  { name: 'Valentino',      logo: 'https://logo.clearbit.com/valentino.com',      category: 'fashion' },
  { name: 'Givenchy',       logo: 'https://logo.clearbit.com/givenchy.com',       category: 'fashion' },
  { name: 'Champion',       logo: 'https://logo.clearbit.com/champion.com',       category: 'fashion' },
  { name: 'Omega',          logo: 'https://logo.clearbit.com/omegawatches.com',   category: 'fashion' },
  { name: 'TAG Heuer',      logo: 'https://logo.clearbit.com/tagheuer.com',       category: 'fashion', aliases: ['tagheuer', 'tag heuer', 'tag'] },

  // ── Automotive ──────────────────────────────────────────────────────────
  { name: 'BMW',            logo: 'https://logo.clearbit.com/bmw.com',            category: 'auto' },
  { name: 'Mercedes-Benz',  logo: 'https://logo.clearbit.com/mercedes-benz.com',  category: 'auto', aliases: ['mercedes', 'benz', 'mercedesbenz'] },
  { name: 'Toyota',         logo: 'https://logo.clearbit.com/toyota.com',         category: 'auto' },
  { name: 'Ferrari',        logo: 'https://logo.clearbit.com/ferrari.com',        category: 'auto' },
  { name: 'Lamborghini',    logo: 'https://logo.clearbit.com/lamborghini.com',    category: 'auto' },
  { name: 'Porsche',        logo: 'https://logo.clearbit.com/porsche.com',        category: 'auto' },
  { name: 'Audi',           logo: 'https://logo.clearbit.com/audi.com',           category: 'auto' },
  { name: 'Honda',          logo: 'https://logo.clearbit.com/honda.com',          category: 'auto' },
  { name: 'Ford',           logo: 'https://logo.clearbit.com/ford.com',           category: 'auto' },
  { name: 'Chevrolet',      logo: 'https://logo.clearbit.com/chevrolet.com',      category: 'auto', aliases: ['chevy'] },
  { name: 'Volkswagen',     logo: 'https://logo.clearbit.com/vw.com',             category: 'auto', aliases: ['vw', 'volkswagon'] },
  { name: 'Hyundai',        logo: 'https://logo.clearbit.com/hyundai.com',        category: 'auto' },
  { name: 'Kia',            logo: 'https://logo.clearbit.com/kia.com',            category: 'auto' },
  { name: 'Nissan',         logo: 'https://logo.clearbit.com/nissan.com',         category: 'auto' },
  { name: 'Mazda',          logo: 'https://logo.clearbit.com/mazda.com',          category: 'auto' },
  { name: 'Subaru',         logo: 'https://logo.clearbit.com/subaru.com',         category: 'auto' },
  { name: 'Jaguar',         logo: 'https://logo.clearbit.com/jaguar.com',         category: 'auto' },
  { name: 'Land Rover',     logo: 'https://logo.clearbit.com/landrover.com',      category: 'auto', aliases: ['landrover'] },
  { name: 'Rolls-Royce',    logo: 'https://logo.clearbit.com/rolls-roycemotorcars.com', category: 'auto', aliases: ['rollsroyce', 'rolls royce'] },
  { name: 'Bentley',        logo: 'https://logo.clearbit.com/bentleymotors.com',  category: 'auto' },
  { name: 'Bugatti',        logo: 'https://logo.clearbit.com/bugatti.com',        category: 'auto' },
  { name: 'Maserati',       logo: 'https://logo.clearbit.com/maserati.com',       category: 'auto' },
  { name: 'Volvo',          logo: 'https://logo.clearbit.com/volvocars.com',      category: 'auto' },
  { name: 'Jeep',           logo: 'https://logo.clearbit.com/jeep.com',           category: 'auto' },
  { name: 'Lexus',          logo: 'https://logo.clearbit.com/lexus.com',          category: 'auto' },
  { name: 'Dodge',          logo: 'https://logo.clearbit.com/dodge.com',          category: 'auto' },
  { name: 'Cadillac',       logo: 'https://logo.clearbit.com/cadillac.com',       category: 'auto' },
  { name: 'Infiniti',       logo: 'https://logo.clearbit.com/infiniti.com',       category: 'auto' },
  { name: 'Acura',          logo: 'https://logo.clearbit.com/acura.com',          category: 'auto' },

  // ── Airlines ────────────────────────────────────────────────────────────
  { name: 'Emirates',          logo: 'https://logo.clearbit.com/emirates.com',        category: 'airline' },
  { name: 'Etihad',            logo: 'https://logo.clearbit.com/etihad.com',          category: 'airline' },
  { name: 'Qatar Airways',     logo: 'https://logo.clearbit.com/qatarairways.com',    category: 'airline', aliases: ['qatar', 'qatarairways'] },
  { name: 'British Airways',   logo: 'https://logo.clearbit.com/britishairways.com',  category: 'airline', aliases: ['ba', 'britishairways'] },
  { name: 'Lufthansa',         logo: 'https://logo.clearbit.com/lufthansa.com',       category: 'airline' },
  { name: 'Air France',        logo: 'https://logo.clearbit.com/airfrance.com',       category: 'airline', aliases: ['airfrance'] },
  { name: 'Delta',             logo: 'https://logo.clearbit.com/delta.com',           category: 'airline' },
  { name: 'United Airlines',   logo: 'https://logo.clearbit.com/united.com',          category: 'airline', aliases: ['united', 'unitedairlines'] },
  { name: 'American Airlines', logo: 'https://logo.clearbit.com/aa.com',              category: 'airline', aliases: ['american', 'americanairlines'] },
  { name: 'Southwest',         logo: 'https://logo.clearbit.com/southwest.com',       category: 'airline' },
  { name: 'Singapore Airlines',logo: 'https://logo.clearbit.com/singaporeair.com',    category: 'airline', aliases: ['singapore', 'singaporeairlines'] },
  { name: 'Turkish Airlines',  logo: 'https://logo.clearbit.com/turkishairlines.com', category: 'airline', aliases: ['turkish', 'turkishairlines'] },
  { name: 'flydubai',          logo: 'https://logo.clearbit.com/flydubai.com',        category: 'airline' },
  { name: 'Air Arabia',        logo: 'https://logo.clearbit.com/airarabia.com',       category: 'airline', aliases: ['airarabia'] },
  { name: 'Cathay Pacific',    logo: 'https://logo.clearbit.com/cathaypacific.com',   category: 'airline', aliases: ['cathay', 'cathaypacific'] },

  // ── Finance ─────────────────────────────────────────────────────────────
  { name: 'Visa',              logo: 'https://logo.clearbit.com/visa.com',             category: 'finance' },
  { name: 'Mastercard',        logo: 'https://logo.clearbit.com/mastercard.com',       category: 'finance' },
  { name: 'American Express',  logo: 'https://logo.clearbit.com/americanexpress.com',  category: 'finance', aliases: ['amex', 'americanexpress'] },
  { name: 'JPMorgan',          logo: 'https://logo.clearbit.com/jpmorgan.com',         category: 'finance', aliases: ['jpmorgan chase', 'jpmc'] },
  { name: 'Goldman Sachs',     logo: 'https://logo.clearbit.com/goldmansachs.com',     category: 'finance', aliases: ['goldmansachs', 'gs'] },
  { name: 'Citibank',          logo: 'https://logo.clearbit.com/citi.com',             category: 'finance', aliases: ['citi'] },
  { name: 'HSBC',              logo: 'https://logo.clearbit.com/hsbc.com',             category: 'finance' },
  { name: 'Barclays',          logo: 'https://logo.clearbit.com/barclays.com',         category: 'finance' },
  { name: 'Wells Fargo',       logo: 'https://logo.clearbit.com/wellsfargo.com',       category: 'finance', aliases: ['wellsfargo'] },
  { name: 'Capital One',       logo: 'https://logo.clearbit.com/capitalone.com',       category: 'finance', aliases: ['capitalone'] },
  { name: 'Revolut',           logo: 'https://logo.clearbit.com/revolut.com',          category: 'finance' },
  { name: 'Wise',              logo: 'https://logo.clearbit.com/wise.com',             category: 'finance' },
  { name: 'Klarna',            logo: 'https://logo.clearbit.com/klarna.com',           category: 'finance' },

  // ── Retail & Consumer ───────────────────────────────────────────────────
  { name: 'IKEA',              logo: 'https://logo.clearbit.com/ikea.com',             category: 'retail' },
  { name: 'Target',            logo: 'https://logo.clearbit.com/target.com',           category: 'retail' },
  { name: 'Walmart',           logo: 'https://logo.clearbit.com/walmart.com',          category: 'retail' },
  { name: 'Costco',            logo: 'https://logo.clearbit.com/costco.com',           category: 'retail' },
  { name: 'Best Buy',          logo: 'https://logo.clearbit.com/bestbuy.com',          category: 'retail', aliases: ['bestbuy'] },
  { name: 'Home Depot',        logo: 'https://logo.clearbit.com/homedepot.com',        category: 'retail', aliases: ['homedepot'] },
  { name: 'LEGO',              logo: 'https://logo.clearbit.com/lego.com',             category: 'retail' },
  { name: 'Dyson',             logo: 'https://logo.clearbit.com/dyson.com',            category: 'retail' },
  { name: 'Philips',           logo: 'https://logo.clearbit.com/philips.com',          category: 'retail' },
  { name: 'Sony',              logo: 'https://logo.clearbit.com/sony.com',             category: 'retail' },
  { name: 'LG',                logo: 'https://logo.clearbit.com/lg.com',               category: 'retail' },
  { name: 'Panasonic',         logo: 'https://logo.clearbit.com/panasonic.com',        category: 'retail' },
  { name: 'Bose',              logo: 'https://logo.clearbit.com/bose.com',             category: 'retail' },

  // ── Entertainment & Media ───────────────────────────────────────────────
  { name: 'Disney',            logo: 'https://logo.clearbit.com/disney.com',           category: 'media' },
  { name: 'Warner Bros',       logo: 'https://logo.clearbit.com/warnerbros.com',       category: 'media', aliases: ['warnerbros', 'wb'] },
  { name: 'Universal',         logo: 'https://logo.clearbit.com/universalpictures.com',category: 'media' },
  { name: 'Paramount',         logo: 'https://logo.clearbit.com/paramount.com',        category: 'media' },
  { name: 'Marvel',            logo: 'https://logo.clearbit.com/marvel.com',           category: 'media' },
  { name: 'HBO',               logo: 'https://logo.clearbit.com/hbo.com',              category: 'media' },
  { name: 'ESPN',              logo: 'https://logo.clearbit.com/espn.com',             category: 'media' },
  { name: 'BBC',               logo: 'https://logo.clearbit.com/bbc.com',              category: 'media' },
  { name: 'CNN',               logo: 'https://logo.clearbit.com/cnn.com',              category: 'media' },
  { name: 'National Geographic',logo:'https://logo.clearbit.com/nationalgeographic.com',category:'media', aliases: ['natgeo', 'nat geo'] },
  { name: 'PlayStation',       logo: 'https://logo.clearbit.com/playstation.com',      category: 'media', aliases: ['ps', 'ps5', 'psn'] },
  { name: 'Xbox',              logo: 'https://logo.clearbit.com/xbox.com',             category: 'media' },
  { name: 'Nintendo',          logo: 'https://logo.clearbit.com/nintendo.com',         category: 'media' },
  { name: 'EA Sports',         logo: 'https://logo.clearbit.com/ea.com',               category: 'media', aliases: ['ea', 'easports'] },
  { name: 'Steam',             logo: 'https://logo.clearbit.com/steampowered.com',     category: 'media' },
  { name: 'Epic Games',        logo: 'https://logo.clearbit.com/epicgames.com',        category: 'media', aliases: ['epicgames', 'epic'] },

  // ── UAE & Middle East ───────────────────────────────────────────────────
  { name: 'Careem',            logo: 'https://logo.clearbit.com/careem.com',           category: 'uae' },
  { name: 'Noon',              logo: 'https://logo.clearbit.com/noon.com',             category: 'uae' },
  { name: 'Emaar',             logo: 'https://logo.clearbit.com/emaar.com',            category: 'uae' },
  { name: 'du',                logo: 'https://logo.clearbit.com/du.ae',                category: 'uae' },
  { name: 'e&',                logo: 'https://logo.clearbit.com/eand.com',             category: 'uae', aliases: ['etisalat', 'eand', 'eandt'] },
  { name: 'ADNOC',             logo: 'https://logo.clearbit.com/adnoc.ae',             category: 'uae' },
  { name: 'DP World',          logo: 'https://logo.clearbit.com/dpworld.com',          category: 'uae', aliases: ['dpworld'] },
  { name: 'Mashreq',           logo: 'https://logo.clearbit.com/mashreq.com',          category: 'uae' },
  { name: 'ENOC',              logo: 'https://logo.clearbit.com/enoc.com',             category: 'uae' },
  { name: 'Aldar',             logo: 'https://logo.clearbit.com/aldar.com',            category: 'uae' },
  { name: 'Jumeirah',          logo: 'https://logo.clearbit.com/jumeirah.com',         category: 'uae' },
  { name: 'Majid Al Futtaim',  logo: 'https://logo.clearbit.com/majidalfuttaim.com',  category: 'uae', aliases: ['maf', 'majidalfuttaim'] },
  { name: 'Meraas',            logo: 'https://logo.clearbit.com/meraas.ae',            category: 'uae' },

  // ── Sports ──────────────────────────────────────────────────────────────
  { name: 'NBA',               logo: 'https://logo.clearbit.com/nba.com',              category: 'sports' },
  { name: 'NFL',               logo: 'https://logo.clearbit.com/nfl.com',              category: 'sports' },
  { name: 'UEFA',              logo: 'https://logo.clearbit.com/uefa.com',             category: 'sports' },
  { name: 'FIFA',              logo: 'https://logo.clearbit.com/fifa.com',             category: 'sports' },
  { name: 'Real Madrid',       logo: 'https://logo.clearbit.com/realmadrid.com',       category: 'sports', aliases: ['realmadrid', 'madrid', 'rm'] },
  { name: 'Barcelona',         logo: 'https://logo.clearbit.com/fcbarcelona.com',      category: 'sports', aliases: ['fcbarcelona', 'barca', 'fc barcelona'] },
  { name: 'Manchester United', logo: 'https://logo.clearbit.com/manutd.com',           category: 'sports', aliases: ['manutd', 'mufc', 'man united', 'man utd'] },
  { name: 'Liverpool',         logo: 'https://logo.clearbit.com/liverpoolfc.com',      category: 'sports', aliases: ['liverpoolfc', 'lfc'] },

  // ── Energy & Industrial ─────────────────────────────────────────────────
  { name: 'Shell',             logo: 'https://logo.clearbit.com/shell.com',            category: 'energy' },
  { name: 'BP',                logo: 'https://logo.clearbit.com/bp.com',               category: 'energy' },
  { name: 'ExxonMobil',        logo: 'https://logo.clearbit.com/exxon.com',            category: 'energy', aliases: ['exxon', 'mobil'] },
  { name: 'Chevron',           logo: 'https://logo.clearbit.com/chevron.com',          category: 'energy' },
  { name: 'Airbus',            logo: 'https://logo.clearbit.com/airbus.com',           category: 'energy' },
  { name: 'Boeing',            logo: 'https://logo.clearbit.com/boeing.com',           category: 'energy' },

  // ── Professional Services ───────────────────────────────────────────────
  { name: 'KPMG',              logo: 'https://logo.clearbit.com/kpmg.com',             category: 'professional' },
  { name: 'Deloitte',          logo: 'https://logo.clearbit.com/deloitte.com',         category: 'professional' },
  { name: 'PwC',               logo: 'https://logo.clearbit.com/pwc.com',              category: 'professional' },
  { name: 'McKinsey',          logo: 'https://logo.clearbit.com/mckinsey.com',         category: 'professional' },
  { name: '3M',                logo: 'https://logo.clearbit.com/3m.com',               category: 'professional' },
  { name: 'Pfizer',            logo: 'https://logo.clearbit.com/pfizer.com',           category: 'professional' },
  { name: 'Moderna',           logo: 'https://logo.clearbit.com/modernatx.com',        category: 'professional' },
  { name: 'Unilever',          logo: 'https://logo.clearbit.com/unilever.com',         category: 'professional' },
  { name: 'Colgate',           logo: 'https://logo.clearbit.com/colgate.com',          category: 'professional' },
  { name: 'Procter & Gamble',  logo: 'https://logo.clearbit.com/pg.com',               category: 'professional', aliases: ['pg', 'p&g', 'procter and gamble', 'procterandgamble'] },
  { name: 'Johnson & Johnson', logo: 'https://logo.clearbit.com/jnj.com',              category: 'professional', aliases: ['jj', 'j&j', 'johnsonandjohnson'] },
];
