// 220+ well-known global brands — domain used to fetch logo from Clearbit
export const LOGOS = [

  // ── Technology ──────────────────────────────────────────────────────────
  { name: 'Apple',         domain: 'apple.com',           category: 'Tech' },
  { name: 'Google',        domain: 'google.com',          category: 'Tech' },
  { name: 'Microsoft',     domain: 'microsoft.com',       category: 'Tech' },
  { name: 'Samsung',       domain: 'samsung.com',         category: 'Tech' },
  { name: 'Amazon',        domain: 'amazon.com',          category: 'Tech' },
  { name: 'Meta',          domain: 'meta.com',            category: 'Tech', aliases: ['facebook'] },
  { name: 'Netflix',       domain: 'netflix.com',         category: 'Tech' },
  { name: 'Spotify',       domain: 'spotify.com',         category: 'Tech' },
  { name: 'Uber',          domain: 'uber.com',            category: 'Tech' },
  { name: 'Airbnb',        domain: 'airbnb.com',          category: 'Tech' },
  { name: 'PayPal',        domain: 'paypal.com',          category: 'Tech' },
  { name: 'YouTube',       domain: 'youtube.com',         category: 'Tech', aliases: ['yt'] },
  { name: 'Instagram',     domain: 'instagram.com',       category: 'Tech', aliases: ['insta'] },
  { name: 'Twitter',       domain: 'twitter.com',         category: 'Tech', aliases: ['x'] },
  { name: 'LinkedIn',      domain: 'linkedin.com',        category: 'Tech' },
  { name: 'Adobe',         domain: 'adobe.com',           category: 'Tech' },
  { name: 'Intel',         domain: 'intel.com',           category: 'Tech' },
  { name: 'Nvidia',        domain: 'nvidia.com',          category: 'Tech' },
  { name: 'Tesla',         domain: 'tesla.com',           category: 'Tech' },
  { name: 'Dell',          domain: 'dell.com',            category: 'Tech' },
  { name: 'HP',            domain: 'hp.com',              category: 'Tech' },
  { name: 'IBM',           domain: 'ibm.com',             category: 'Tech' },
  { name: 'Oracle',        domain: 'oracle.com',          category: 'Tech' },
  { name: 'Cisco',         domain: 'cisco.com',           category: 'Tech' },
  { name: 'Zoom',          domain: 'zoom.us',             category: 'Tech' },
  { name: 'Slack',         domain: 'slack.com',           category: 'Tech' },
  { name: 'Dropbox',       domain: 'dropbox.com',         category: 'Tech' },
  { name: 'Reddit',        domain: 'reddit.com',          category: 'Tech' },
  { name: 'TikTok',        domain: 'tiktok.com',          category: 'Tech' },
  { name: 'Snapchat',      domain: 'snapchat.com',        category: 'Tech' },
  { name: 'Pinterest',     domain: 'pinterest.com',       category: 'Tech' },
  { name: 'Discord',       domain: 'discord.com',         category: 'Tech' },
  { name: 'Twitch',        domain: 'twitch.tv',           category: 'Tech' },
  { name: 'eBay',          domain: 'ebay.com',            category: 'Tech' },
  { name: 'Shopify',       domain: 'shopify.com',         category: 'Tech' },
  { name: 'Stripe',        domain: 'stripe.com',          category: 'Tech' },
  { name: 'WhatsApp',      domain: 'whatsapp.com',        category: 'Tech' },
  { name: 'Telegram',      domain: 'telegram.org',        category: 'Tech' },
  { name: 'GitHub',        domain: 'github.com',          category: 'Tech' },
  { name: 'Figma',         domain: 'figma.com',           category: 'Tech' },
  { name: 'Notion',        domain: 'notion.so',           category: 'Tech' },
  { name: 'Canva',         domain: 'canva.com',           category: 'Tech' },
  { name: 'Lyft',          domain: 'lyft.com',            category: 'Tech' },
  { name: 'Coinbase',      domain: 'coinbase.com',        category: 'Tech' },
  { name: 'Robinhood',     domain: 'robinhood.com',       category: 'Tech' },

  // ── Food & Beverage ─────────────────────────────────────────────────────
  { name: "McDonald's",    domain: 'mcdonalds.com',       category: 'Food', aliases: ['mcdonalds', 'mcdonald'] },
  { name: 'Coca-Cola',     domain: 'coca-cola.com',       category: 'Food', aliases: ['coke', 'cocacola', 'coca cola'] },
  { name: 'Pepsi',         domain: 'pepsi.com',           category: 'Food' },
  { name: 'Starbucks',     domain: 'starbucks.com',       category: 'Food' },
  { name: 'KFC',           domain: 'kfc.com',             category: 'Food' },
  { name: 'Subway',        domain: 'subway.com',          category: 'Food' },
  { name: 'Pizza Hut',     domain: 'pizzahut.com',        category: 'Food', aliases: ['pizzahut'] },
  { name: "Domino's",      domain: 'dominos.com',         category: 'Food', aliases: ['dominos', 'domino'] },
  { name: 'Burger King',   domain: 'burgerking.com',      category: 'Food', aliases: ['burgerking', 'bk'] },
  { name: 'Heineken',      domain: 'heineken.com',        category: 'Food' },
  { name: 'Red Bull',      domain: 'redbull.com',         category: 'Food', aliases: ['redbull'] },
  { name: 'Monster',       domain: 'monsterenergy.com',   category: 'Food' },
  { name: 'Nescafe',       domain: 'nescafe.com',         category: 'Food' },
  { name: 'Nutella',       domain: 'nutella.com',         category: 'Food' },
  { name: 'Heinz',         domain: 'heinz.com',           category: 'Food' },
  { name: "Kellogg's",     domain: 'kelloggs.com',        category: 'Food', aliases: ['kelloggs'] },
  { name: 'Nestlé',        domain: 'nestle.com',          category: 'Food', aliases: ['nestle'] },
  { name: 'Pringles',      domain: 'pringles.com',        category: 'Food' },
  { name: "Lay's",         domain: 'lays.com',            category: 'Food', aliases: ['lays'] },
  { name: 'Oreo',          domain: 'oreo.com',            category: 'Food' },
  { name: 'Tabasco',       domain: 'tabasco.com',         category: 'Food' },
  { name: 'Budweiser',     domain: 'budweiser.com',       category: 'Food' },
  { name: 'Corona',        domain: 'corona.com',          category: 'Food' },
  { name: "Dunkin'",       domain: 'dunkindonuts.com',    category: 'Food', aliases: ['dunkin', 'dunkindonuts'] },
  { name: 'Chipotle',      domain: 'chipotle.com',        category: 'Food' },
  { name: 'Shake Shack',   domain: 'shakeshack.com',      category: 'Food', aliases: ['shakeshack'] },
  { name: 'Tim Hortons',   domain: 'timhortons.com',      category: 'Food', aliases: ['timhortons'] },
  { name: 'Five Guys',     domain: 'fiveguys.com',        category: 'Food', aliases: ['fiveguys'] },
  { name: 'Absolut',       domain: 'absolut.com',         category: 'Food' },
  { name: 'Bacardi',       domain: 'bacardi.com',         category: 'Food' },

  // ── Fashion & Luxury ────────────────────────────────────────────────────
  { name: 'Nike',           domain: 'nike.com',           category: 'Fashion' },
  { name: 'Adidas',         domain: 'adidas.com',         category: 'Fashion' },
  { name: 'Gucci',          domain: 'gucci.com',          category: 'Fashion' },
  { name: 'Louis Vuitton',  domain: 'louisvuitton.com',   category: 'Fashion', aliases: ['lv', 'louisvuitton'] },
  { name: 'Zara',           domain: 'zara.com',           category: 'Fashion' },
  { name: 'H&M',            domain: 'hm.com',             category: 'Fashion', aliases: ['hm', 'handm'] },
  { name: 'Prada',          domain: 'prada.com',          category: 'Fashion' },
  { name: 'Versace',        domain: 'versace.com',        category: 'Fashion' },
  { name: 'Burberry',       domain: 'burberry.com',       category: 'Fashion' },
  { name: 'Ralph Lauren',   domain: 'ralphlauren.com',    category: 'Fashion', aliases: ['ralphlauren', 'polo'] },
  { name: 'Tommy Hilfiger', domain: 'tommy.com',          category: 'Fashion', aliases: ['tommy', 'tommyhilfiger'] },
  { name: 'Calvin Klein',   domain: 'calvinklein.com',    category: 'Fashion', aliases: ['ck', 'calvinklein'] },
  { name: "Levi's",         domain: 'levi.com',           category: 'Fashion', aliases: ['levis', 'levi'] },
  { name: 'New Balance',    domain: 'newbalance.com',     category: 'Fashion', aliases: ['newbalance', 'nb'] },
  { name: 'Puma',           domain: 'puma.com',           category: 'Fashion' },
  { name: 'Reebok',         domain: 'reebok.com',         category: 'Fashion' },
  { name: 'Under Armour',   domain: 'underarmour.com',    category: 'Fashion', aliases: ['ua', 'underarmour'] },
  { name: 'Rolex',          domain: 'rolex.com',          category: 'Fashion' },
  { name: 'Chanel',         domain: 'chanel.com',         category: 'Fashion' },
  { name: 'Hermès',         domain: 'hermes.com',         category: 'Fashion', aliases: ['hermes'] },
  { name: 'Dior',           domain: 'dior.com',           category: 'Fashion' },
  { name: 'Balenciaga',     domain: 'balenciaga.com',     category: 'Fashion' },
  { name: 'Supreme',        domain: 'supremenewyork.com', category: 'Fashion' },
  { name: 'Vans',           domain: 'vans.com',           category: 'Fashion' },
  { name: 'Converse',       domain: 'converse.com',       category: 'Fashion' },
  { name: 'Timberland',     domain: 'timberland.com',     category: 'Fashion' },
  { name: 'The North Face', domain: 'thenorthface.com',   category: 'Fashion', aliases: ['northface', 'tnf', 'north face'] },
  { name: 'Patagonia',      domain: 'patagonia.com',      category: 'Fashion' },
  { name: 'Fendi',          domain: 'fendi.com',          category: 'Fashion' },
  { name: 'Valentino',      domain: 'valentino.com',      category: 'Fashion' },
  { name: 'Givenchy',       domain: 'givenchy.com',       category: 'Fashion' },
  { name: 'Champion',       domain: 'champion.com',       category: 'Fashion' },
  { name: 'Omega',          domain: 'omegawatches.com',   category: 'Fashion' },
  { name: 'TAG Heuer',      domain: 'tagheuer.com',       category: 'Fashion', aliases: ['tagheuer', 'tag heuer', 'tag'] },

  // ── Automotive ──────────────────────────────────────────────────────────
  { name: 'BMW',            domain: 'bmw.com',            category: 'Auto' },
  { name: 'Mercedes-Benz',  domain: 'mercedes-benz.com',  category: 'Auto', aliases: ['mercedes', 'benz', 'mercedesbenz'] },
  { name: 'Toyota',         domain: 'toyota.com',         category: 'Auto' },
  { name: 'Ferrari',        domain: 'ferrari.com',        category: 'Auto' },
  { name: 'Lamborghini',    domain: 'lamborghini.com',    category: 'Auto' },
  { name: 'Porsche',        domain: 'porsche.com',        category: 'Auto' },
  { name: 'Audi',           domain: 'audi.com',           category: 'Auto' },
  { name: 'Honda',          domain: 'honda.com',          category: 'Auto' },
  { name: 'Ford',           domain: 'ford.com',           category: 'Auto' },
  { name: 'Chevrolet',      domain: 'chevrolet.com',      category: 'Auto', aliases: ['chevy'] },
  { name: 'Volkswagen',     domain: 'vw.com',             category: 'Auto', aliases: ['vw', 'volkswagon'] },
  { name: 'Hyundai',        domain: 'hyundai.com',        category: 'Auto' },
  { name: 'Kia',            domain: 'kia.com',            category: 'Auto' },
  { name: 'Nissan',         domain: 'nissan.com',         category: 'Auto' },
  { name: 'Mazda',          domain: 'mazda.com',          category: 'Auto' },
  { name: 'Subaru',         domain: 'subaru.com',         category: 'Auto' },
  { name: 'Jaguar',         domain: 'jaguar.com',         category: 'Auto' },
  { name: 'Land Rover',     domain: 'landrover.com',      category: 'Auto', aliases: ['landrover'] },
  { name: 'Rolls-Royce',    domain: 'rolls-roycemotorcars.com', category: 'Auto', aliases: ['rollsroyce', 'rolls royce'] },
  { name: 'Bentley',        domain: 'bentleymotors.com',  category: 'Auto' },
  { name: 'Bugatti',        domain: 'bugatti.com',        category: 'Auto' },
  { name: 'Maserati',       domain: 'maserati.com',       category: 'Auto' },
  { name: 'Volvo',          domain: 'volvocars.com',      category: 'Auto' },
  { name: 'Jeep',           domain: 'jeep.com',           category: 'Auto' },
  { name: 'Lexus',          domain: 'lexus.com',          category: 'Auto' },
  { name: 'Dodge',          domain: 'dodge.com',          category: 'Auto' },
  { name: 'Cadillac',       domain: 'cadillac.com',       category: 'Auto' },
  { name: 'Infiniti',       domain: 'infiniti.com',       category: 'Auto' },
  { name: 'Acura',          domain: 'acura.com',          category: 'Auto' },

  // ── Airlines ────────────────────────────────────────────────────────────
  { name: 'Emirates',           domain: 'emirates.com',        category: 'Airline' },
  { name: 'Etihad',             domain: 'etihad.com',          category: 'Airline' },
  { name: 'Qatar Airways',      domain: 'qatarairways.com',    category: 'Airline', aliases: ['qatar', 'qatarairways'] },
  { name: 'British Airways',    domain: 'britishairways.com',  category: 'Airline', aliases: ['ba', 'britishairways'] },
  { name: 'Lufthansa',          domain: 'lufthansa.com',       category: 'Airline' },
  { name: 'Air France',         domain: 'airfrance.com',       category: 'Airline', aliases: ['airfrance'] },
  { name: 'Delta',              domain: 'delta.com',           category: 'Airline' },
  { name: 'United Airlines',    domain: 'united.com',          category: 'Airline', aliases: ['united', 'unitedairlines'] },
  { name: 'American Airlines',  domain: 'aa.com',              category: 'Airline', aliases: ['american', 'americanairlines'] },
  { name: 'Southwest',          domain: 'southwest.com',       category: 'Airline' },
  { name: 'Singapore Airlines', domain: 'singaporeair.com',    category: 'Airline', aliases: ['singapore', 'singaporeairlines'] },
  { name: 'Turkish Airlines',   domain: 'turkishairlines.com', category: 'Airline', aliases: ['turkish', 'turkishairlines'] },
  { name: 'flydubai',           domain: 'flydubai.com',        category: 'Airline' },
  { name: 'Air Arabia',         domain: 'airarabia.com',       category: 'Airline', aliases: ['airarabia'] },
  { name: 'Cathay Pacific',     domain: 'cathaypacific.com',   category: 'Airline', aliases: ['cathay', 'cathaypacific'] },

  // ── Finance ─────────────────────────────────────────────────────────────
  { name: 'Visa',              domain: 'visa.com',             category: 'Finance' },
  { name: 'Mastercard',        domain: 'mastercard.com',       category: 'Finance' },
  { name: 'American Express',  domain: 'americanexpress.com',  category: 'Finance', aliases: ['amex', 'americanexpress'] },
  { name: 'JPMorgan',          domain: 'jpmorgan.com',         category: 'Finance', aliases: ['jpmorgan chase', 'jpmc'] },
  { name: 'Goldman Sachs',     domain: 'goldmansachs.com',     category: 'Finance', aliases: ['goldmansachs', 'gs'] },
  { name: 'Citibank',          domain: 'citi.com',             category: 'Finance', aliases: ['citi'] },
  { name: 'HSBC',              domain: 'hsbc.com',             category: 'Finance' },
  { name: 'Barclays',          domain: 'barclays.com',         category: 'Finance' },
  { name: 'Wells Fargo',       domain: 'wellsfargo.com',       category: 'Finance', aliases: ['wellsfargo'] },
  { name: 'Capital One',       domain: 'capitalone.com',       category: 'Finance', aliases: ['capitalone'] },
  { name: 'Revolut',           domain: 'revolut.com',          category: 'Finance' },
  { name: 'Wise',              domain: 'wise.com',             category: 'Finance' },
  { name: 'Klarna',            domain: 'klarna.com',           category: 'Finance' },

  // ── Retail & Consumer ───────────────────────────────────────────────────
  { name: 'IKEA',              domain: 'ikea.com',             category: 'Retail' },
  { name: 'Target',            domain: 'target.com',           category: 'Retail' },
  { name: 'Walmart',           domain: 'walmart.com',          category: 'Retail' },
  { name: 'Costco',            domain: 'costco.com',           category: 'Retail' },
  { name: 'Best Buy',          domain: 'bestbuy.com',          category: 'Retail', aliases: ['bestbuy'] },
  { name: 'Home Depot',        domain: 'homedepot.com',        category: 'Retail', aliases: ['homedepot'] },
  { name: 'LEGO',              domain: 'lego.com',             category: 'Retail' },
  { name: 'Dyson',             domain: 'dyson.com',            category: 'Retail' },
  { name: 'Philips',           domain: 'philips.com',          category: 'Retail' },
  { name: 'Sony',              domain: 'sony.com',             category: 'Retail' },
  { name: 'LG',                domain: 'lg.com',               category: 'Retail' },
  { name: 'Panasonic',         domain: 'panasonic.com',        category: 'Retail' },
  { name: 'Bose',              domain: 'bose.com',             category: 'Retail' },

  // ── Entertainment & Media ───────────────────────────────────────────────
  { name: 'Disney',            domain: 'disney.com',           category: 'Media' },
  { name: 'Warner Bros',       domain: 'warnerbros.com',       category: 'Media', aliases: ['warnerbros', 'wb'] },
  { name: 'Universal',         domain: 'universalpictures.com',category: 'Media' },
  { name: 'Paramount',         domain: 'paramount.com',        category: 'Media' },
  { name: 'Marvel',            domain: 'marvel.com',           category: 'Media' },
  { name: 'HBO',               domain: 'hbo.com',              category: 'Media' },
  { name: 'ESPN',              domain: 'espn.com',             category: 'Media' },
  { name: 'BBC',               domain: 'bbc.com',              category: 'Media' },
  { name: 'CNN',               domain: 'cnn.com',              category: 'Media' },
  { name: 'National Geographic',domain:'nationalgeographic.com',category:'Media', aliases: ['natgeo', 'nat geo'] },
  { name: 'PlayStation',       domain: 'playstation.com',      category: 'Media', aliases: ['ps', 'ps5', 'psn'] },
  { name: 'Xbox',              domain: 'xbox.com',             category: 'Media' },
  { name: 'Nintendo',          domain: 'nintendo.com',         category: 'Media' },
  { name: 'EA Sports',         domain: 'ea.com',               category: 'Media', aliases: ['ea', 'easports'] },
  { name: 'Steam',             domain: 'steampowered.com',     category: 'Media' },
  { name: 'Epic Games',        domain: 'epicgames.com',        category: 'Media', aliases: ['epicgames', 'epic'] },

  // ── UAE & Middle East ───────────────────────────────────────────────────
  { name: 'Careem',            domain: 'careem.com',           category: 'UAE' },
  { name: 'Noon',              domain: 'noon.com',             category: 'UAE' },
  { name: 'Emaar',             domain: 'emaar.com',            category: 'UAE' },
  { name: 'du',                domain: 'du.ae',                category: 'UAE' },
  { name: 'e&',                domain: 'eand.com',             category: 'UAE', aliases: ['etisalat', 'eand'] },
  { name: 'ADNOC',             domain: 'adnoc.ae',             category: 'UAE' },
  { name: 'DP World',          domain: 'dpworld.com',          category: 'UAE', aliases: ['dpworld'] },
  { name: 'Mashreq',           domain: 'mashreq.com',          category: 'UAE' },
  { name: 'ENOC',              domain: 'enoc.com',             category: 'UAE' },
  { name: 'Aldar',             domain: 'aldar.com',            category: 'UAE' },
  { name: 'Jumeirah',          domain: 'jumeirah.com',         category: 'UAE' },
  { name: 'Majid Al Futtaim',  domain: 'majidalfuttaim.com',  category: 'UAE', aliases: ['maf', 'majidalfuttaim'] },
  { name: 'Meraas',            domain: 'meraas.ae',            category: 'UAE' },

  // ── Sports ──────────────────────────────────────────────────────────────
  { name: 'NBA',               domain: 'nba.com',              category: 'Sports' },
  { name: 'NFL',               domain: 'nfl.com',              category: 'Sports' },
  { name: 'UEFA',              domain: 'uefa.com',             category: 'Sports' },
  { name: 'FIFA',              domain: 'fifa.com',             category: 'Sports' },
  { name: 'Real Madrid',       domain: 'realmadrid.com',       category: 'Sports', aliases: ['realmadrid', 'madrid', 'rm'] },
  { name: 'Barcelona',         domain: 'fcbarcelona.com',      category: 'Sports', aliases: ['fcbarcelona', 'barca', 'fc barcelona'] },
  { name: 'Manchester United', domain: 'manutd.com',           category: 'Sports', aliases: ['manutd', 'mufc', 'man united', 'man utd'] },
  { name: 'Liverpool',         domain: 'liverpoolfc.com',      category: 'Sports', aliases: ['liverpoolfc', 'lfc'] },

  // ── Energy & Industrial ─────────────────────────────────────────────────
  { name: 'Shell',             domain: 'shell.com',            category: 'Energy' },
  { name: 'BP',                domain: 'bp.com',               category: 'Energy' },
  { name: 'ExxonMobil',        domain: 'exxon.com',            category: 'Energy', aliases: ['exxon', 'mobil'] },
  { name: 'Chevron',           domain: 'chevron.com',          category: 'Energy' },
  { name: 'Airbus',            domain: 'airbus.com',           category: 'Energy' },
  { name: 'Boeing',            domain: 'boeing.com',           category: 'Energy' },

  // ── Professional Services ───────────────────────────────────────────────
  { name: 'KPMG',              domain: 'kpmg.com',             category: 'Professional' },
  { name: 'Deloitte',          domain: 'deloitte.com',         category: 'Professional' },
  { name: 'PwC',               domain: 'pwc.com',              category: 'Professional' },
  { name: 'McKinsey',          domain: 'mckinsey.com',         category: 'Professional' },
  { name: '3M',                domain: '3m.com',               category: 'Professional' },
  { name: 'Pfizer',            domain: 'pfizer.com',           category: 'Professional' },
  { name: 'Moderna',           domain: 'modernatx.com',        category: 'Professional' },
  { name: 'Unilever',          domain: 'unilever.com',         category: 'Professional' },
  { name: 'Colgate',           domain: 'colgate.com',          category: 'Professional' },
  { name: 'Procter & Gamble',  domain: 'pg.com',               category: 'Professional', aliases: ['pg', 'procter and gamble', 'procterandgamble'] },
  { name: 'Johnson & Johnson', domain: 'jnj.com',              category: 'Professional', aliases: ['jj', 'johnsonandjohnson'] },
];
