export const EMOJI_PHRASES = [
  { emojis: '🌊🏄‍♂️🌊', answer: 'SURFING', hint: 'Water sport' },
  { emojis: '🌙⭐🌙', answer: 'STARRY NIGHT', hint: 'Van Gogh painting' },
  { emojis: '🍎📱💻', answer: 'APPLE', hint: 'Tech company' },
  { emojis: '🦁👑🌍', answer: 'LION KING', hint: 'Disney movie' },
  { emojis: '❄️👸🏰', answer: 'FROZEN', hint: 'Animated film' },
  { emojis: '🕷️👦🏙️', answer: 'SPIDER-MAN', hint: 'Marvel superhero' },
  { emojis: '🦇🤵🏙️', answer: 'BATMAN', hint: 'DC superhero' },
  { emojis: '🚀🌑👨‍🚀', answer: 'MOON LANDING', hint: 'Historic event' },
  { emojis: '⚡🧙📚', answer: 'HARRY POTTER', hint: 'Wizarding world' },
  { emojis: '💍🧝🏔️', answer: 'LORD OF THE RINGS', hint: 'Epic fantasy' },
  { emojis: '🎸🎤🎶', answer: 'ROCK STAR', hint: 'Music career' },
  { emojis: '🍕🇮🇹👨‍🍳', answer: 'PIZZA CHEF', hint: 'Italian cook' },
  { emojis: '🐉🔥🏰', answer: 'FIRE DRAGON', hint: 'Fantasy beast' },
  { emojis: '🌈🦄✨', answer: 'UNICORN', hint: 'Mythical creature' },
  { emojis: '🎃👻🕷️', answer: 'HALLOWEEN', hint: 'Spooky holiday' },
  { emojis: '🎄🎁⭐', answer: 'CHRISTMAS', hint: 'Winter holiday' },
  { emojis: '💀☠️🏴‍☠️', answer: 'PIRATES', hint: 'Seafarers' },
  { emojis: '🧲💡⚡', answer: 'ELECTRICITY', hint: 'Power source' },
  { emojis: '🐋🌊🌊', answer: 'WHALE', hint: 'Ocean giant' },
  { emojis: '🌋💥🔴', answer: 'ERUPTION', hint: 'Volcanic event' },
  { emojis: '🎯🎳🎱', answer: 'BOWLING', hint: 'Pin sport' },
  { emojis: '🏋️‍♂️💪🥇', answer: 'WEIGHTLIFTING', hint: 'Olympic sport' },
  { emojis: '🐝🍯🌸', answer: 'HONEYBEE', hint: 'Pollinator' },
  { emojis: '🌍✈️🧳', answer: 'WORLD TRAVEL', hint: 'Adventure' },
  { emojis: '🧩🤔💡', answer: 'PUZZLE', hint: 'Brain teaser' },
  { emojis: '🎭😂😢', answer: 'COMEDY', hint: 'Performance art' },
  { emojis: '🏖️☀️🌴', answer: 'BEACH DAY', hint: 'Summer outing' },
  { emojis: '🐧❄️🏔️', answer: 'ANTARCTICA', hint: 'Icy continent' },
  { emojis: '🍦🌞😊', answer: 'ICE CREAM', hint: 'Frozen treat' },
  { emojis: '🚂💨🛤️', answer: 'TRAIN JOURNEY', hint: 'Rail travel' },
];
