import { seededRandom, getTodaySeed } from '../../lib/utils.js';

// Curated answer words — these are picked as daily targets
export const ANSWER_WORDS = [
  'about','above','abuse','actor','acute','admit','adopt','adult','after','again',
  'agent','agree','ahead','alarm','album','alert','alien','align','alike','alive',
  'alley','allow','alone','along','altar','alter','angel','anger','angle','angry',
  'ankle','apart','apple','apply','arena','argue','arise','armor','aroma','arrow',
  'arson','aside','atlas','attic','audio','audit','avoid','awake','award','aware',
  'awful','badge','baker','basic','basis','batch','beach','beard','beast','began',
  'begin','being','below','bench','birth','black','blade','blame','bland','blank',
  'blast','blaze','bleed','blend','bless','blind','block','blood','bloom','blown',
  'board','boast','bonus','boost','booth','bored','bound','brain','brand','brave',
  'bread','break','breed','brick','bride','brief','bring','broad','broke','brook',
  'brown','build','built','bunch','burst','buyer','cabin','camel','candy','cargo',
  'carry','catch','cause','cedar','chain','chair','chaos','chart','chase','cheap',
  'check','cheek','chess','chest','chief','child','chips','choir','chord','chose',
  'civic','civil','claim','class','clean','clear','clerk','click','cliff','climb',
  'cling','clock','close','cloth','cloud','clown','coach','coast','cobra','comet',
  'comic','comma','coral','couch','could','count','court','cover','crack','craft',
  'crash','crazy','cream','creek','crime','crisp','cross','crowd','crown','cruel',
  'crush','cubic','curve','cycle','daily','dance','datum','dealt','death','debut',
  'decor','defer','delay','depot','depth','derby','devil','dirty','disco','ditch',
  'dodge','dolls','doubt','dough','draft','drain','drama','drank','drape','dream',
  'dress','drift','drink','drive','drone','drove','drums','dryer','eager','eagle',
  'early','earth','eerie','eight','elect','elbow','elder','elite','elves','empty',
  'enemy','enjoy','enter','entry','equal','error','essay','event','every','exact',
  'exist','extra','fable','faith','fancy','fatal','fault','feast','fence','ferry',
  'fever','field','fifth','fifty','fight','final','first','fixed','flame','flash',
  'flask','fleet','flesh','float','floor','floss','flour','flown','fluid','flute',
  'focal','foggy','folio','folks','force','forge','found','frail','frame','fraud',
  'freak','freed','fresh','front','frost','fruit','fully','ghost','giant','given',
  'gland','glass','glaze','gleam','glide','gloom','gloss','glove','going','grace',
  'grade','graft','grain','grand','grant','grasp','grass','grate','graze','greed',
  'greet','grief','grind','groan','gross','grout','grown','guard','guide','guild',
  'guilt','guise','gulch','gully','habit','happy','harsh','haste','haven','heart',
  'heavy','herbs','hotel','hotel','hound','house','human','humor','hunch','hyena',
  'icing','ideal','image','imply','inbox','index','indie','infer','ingot','inlay',
  'inner','input','irony','issue','ivory','jazzy','jewel','joker','joint','joust',
  'judge','juice','juicy','kabob','karma','kiosk','knack','knife','knock','known',
  'label','lance','large','laser','later','laugh','layer','learn','lease','leave',
  'legal','lemon','level','light','limit','linen','liner','liver','local','lodge',
  'logic','loose','lower','loyal','lucky','lunar','lunch','lyric','magic','major',
  'maker','manor','maple','march','masse','match','mayor','media','mercy','merge',
  'merit','metal','model','money','monks','moral','mossy','motif','motor','mount',
  'mouse','mouth','movie','mulch','multi','mural','music','nadir','naive','nerve',
  'never','newly','night','noble','noise','north','noted','novel','nurse','nymph',
  'occur','ocean','offal','often','orbit','order','other','otter','overt','owner',
  'ozone','paint','panel','paper','parry','party','pasta','patch','pause','payee',
  'peace','pearl','pedal','penny','perch','phase','phone','photo','piece','pilot',
  'pixel','pizza','place','plain','plane','plant','plaza','plead','pluck','plumb',
  'plume','plump','plunge','point','polar','polka','poppy','porch','posed','power',
  'press','price','pride','prime','print','prism','privy','prize','probe','prone',
  'proof','prose','proud','prove','psalm','punch','pupil','purge','queen','query',
  'quest','queue','quick','quiet','quota','quote','rabbi','radar','radio','raise',
  'rally','ranch','range','rapid','raven','reach','react','realm','rebel','recap',
  'reign','relax','relay','remix','renal','renew','repay','repel','rerun','reset',
  'resin','rider','ridge','rifle','right','rigid','risky','rivet','roast','robot',
  'rocky','rouge','rough','round','route','royal','ruins','ruler','rural','safer',
  'saint','salad','sauce','scale','scare','scene','scent','scout','seize','sense',
  'serve','seven','shade','shake','shale','shame','share','shark','sharp','sheer',
  'shone','shore','short','shout','shove','sight','silly','since','sixth','sized',
  'skill','skirt','skull','slack','slate','sleek','sleet','slept','slice','slide',
  'slim','slope','small','smart','smash','smear','smell','smelt','smile','smock',
  'smoke','snack','snail','snake','snare','sneak','sneer','sniff','snore','solar',
  'solid','solve','sonic','space','spare','spark','speak','speed','spell','spend',
  'spice','spill','spine','spite','spoon','sport','spray','squad','stack','staff',
  'stage','stain','stale','stall','stare','start','state','stays','steal','steam',
  'steel','steep','steer','stern','stick','stiff','still','stock','stomp','stone',
  'store','storm','story','stove','strap','stray','strip','stuck','study','stump',
  'stunt','style','sugar','suite','super','surge','swamp','swear','sweat','sweep',
  'sweet','swept','swift','swirl','sword','swore','swung','syrup','table','taken',
  'tally','taste','teach','tense','tepid','terms','thank','thatch','theme','there',
  'these','thick','thing','think','third','those','three','threw','throw','thumb',
  'tiger','tight','timed','timer','tired','title','today','token','tonic','tooth',
  'torch','total','touch','tough','towel','tower','toxic','trace','track','trade',
  'trail','train','trait','trawl','trend','trial','tribe','trick','tried','troop',
  'troth','truck','truly','trump','trust','truth','tumor','tuner','twist','tying',
  'ultra','under','unify','union','until','upper','upset','urban','usage','usual',
  'utter','valid','value','valve','vault','veiny','verse','vicar','viola','viral',
  'virus','vista','vital','vivid','vodka','voice','voila','voter','vying','waded',
  'wafer','wager','wagon','waste','watch','water','weary','weave','weird','whale',
  'wheat','wheel','where','which','while','white','whole','whose','widen','widow',
  'witch','woman','women','woods','world','worry','worst','worth','would','wound',
  'wrath','wrist','wrote','yacht','yield','young','youth','zebra','zonal',
];

// All valid guesses — much larger dictionary (any real 5-letter word)
const EXTRA_VALID = [
  'aahed','aalii','abaci','aback','abaft','abase','abash','abate','abbey','abbot',
  'abhor','abide','abies','abler','abode','abort','abram','abysm','abyss','ached',
  'aches','achoo','acids','acorn','acrid','acted','acumen','adage','added','adder',
  'addio','adept','adieu','adman','adobe','agave','aghast','agile','aging','aglow',
  'agony','agora','agued','ahold','aided','aimer','airer','aitch','algae','alibi',
  'alight','aloft','aloof','altar','amaze','amber','amble','amend','amiss','among',
  'amuck','ample','annoy','antic','anvil','aphid','apish','apnea','apron','aptly',
  'arbor','ardor','argot','armor','artery','artsy','ascot','ashen','aspen','assay',
  'astir','atilt','atone','atria','attar','auger','augur','avail','avian','avid',
  'avoid','awash','awing','awoke','awry','azoth','azure','babel','badly','bagel',
  'baggy','baize','balmy','banal','bandy','bared','baron','basal','baste','bawdy',
  'bawl','bayou','beady','beech','beefy','befit','befog','belle','bezel','bidet',
  'bigot','bilge','binge','biome','birch','bison','bitty','blabs','blain','blimp',
  'blunt','blurb','blurt','blush','boggy','bogus','bossy','botch','bower','braid',
  'brash','brawn','braze','bream','briny','brisk','broil','brome','brood','broth',
  'brows','budge','bumpy','bunny','burly','bushy','butch','butts','bylaw','byway',
  'cabal','cadge','cajon','calyx','cameo','canal','caper','carob','carol','caste',
  'catty','cavil','cedar','cello','chafe','champ','chard','chary','chasm','chewy',
  'chide','chill','chimp','cigar','circa','clasp','cleat','cleft','clerk','clime',
  'clomp','clone','clop','clout','clued','codex','coerce','cofax','coign','colle',
  'colon','color','combo','comfy','compo','conch','condo','coney','confer','copse',
  'corny','creep','crimp','crisp','croak','crone','crook','crude','crumble','crypt',
  'cupid','curly','curry','darns','daunt','decal','decry','delta','dense','depot',
  'deign','deity','delve','demon','derma','detox','deuce','dimly','divvy','ditty',
  'divot','djinn','dodgy','dogma','dolce','dolor','dopey','dorky','dowdy','downy',
  'dowse','ducky','dunno','duped','duple','dusky','dusty','dwelt','dying','eased',
  'eaten','edgy','egged','egret','eking','elide','elope','emcee','emote','envoy',
  'epact','epoch','erode','evade','evict','exact','exalt','extol','eying','facet',
  'farce','favor','feast','feign','femur','fiend','filch','filmy','finch','fizzy',
  'fjord','flair','flaky','bland','flier','flinch','flint','flivvy','flong','flop',
  'flora','floss','flout','foamy','fogbound','foray','forgo','forte','found','frill',
  'frond','froze','fudge','fungi','funky','furry','gavel','gaudy','gauze','gavel',
  'geese','giddy','girth','given','glint','gloat','gloomy','godly','gorge','gouge',
  'gourd','graft','graze','grebe','grimy','grime','gripe','groan','groin','grope',
  'grove','gruff','grunge','guano','gummy','gutsy','gypsy','haiku','halve','handy',
  'hardy','harpy','harry','heady','heist','hertz','hippo','hoary','hobby','holly',
  'homer','honor','hooky','hovel','humid','husky','hutch','idyll','igloo','imago',
  'imply','inane','incur','indie','inept','inert','infix','ingot','inurn','iamb',
  'irate','itchy','ivory','jaded','jaunt','jazzy','jibed','jiffy','jimmy','juror',
  'kaput','ketch','kitty','knave','knead','kneel','knelt','knob','knoll','laced',
  'laity','lanky','lapel','lardy','lasso','latch','latte','laver','leafy','leaky',
  'lean','leapt','leery','lemma','liege','livid','llama','loamy','loath','lofty',
  'loopy','lorry','lousy','lumen','lumpy','lusty','madly','maize','manly','mangy',
  'maverick','mealy','mealy','messy','minty','mirth','misty','mocha','moldy','molten',
  'money','moody','moose','mucky','muddy','muggy','mushy','musky','musty','myrrh',
  'nabob','nanny','nasty','natty','navel','nervy','nifty','nippy','nitty','nodal',
  'nomad','nosey','notch','nutty','nymph','oaken','oaken','offal','ohm','olive',
  'onrush','optic','orate','orchid','oriel','orlon','ounce','ovary','ovoid','pagan',
  'paddy','pasty','patsy','patty','payoff','pebble','peeve','perky','petty','piety',
  'piggy','piney','piper','pipit','pique','plaid','plait','plank','plead','plink',
  'plonk','pluck','plunk','podium','pokey','polyp','poncho','poplar','poppy','potty',
  'pouty','primp','prude','puffy','pulpy','punky','pushy','pygmy','quaff','qualm',
  'quash','quaff','rabid','rajah','rammy','rancid','randy','rangy','raspy','ratty',
  'rebus','rebut','reedy','renew','repro','retch','rhyme','ripen','risky','ropey',
  'roost','rowdy','ruddy','rugby','runny','rushy','sable','saggy','salty','sandy',
  'sappy','sarky','sassy','savvy','scald','scaly','scalp','scant','scorn','scour',
  'scram','scrawl','scrum','seedy','seraph','shady','shaky','shaly','shank','shoal',
  'sigma','silky','silty','simmer','sixty','skiff','skimp','skirr','skulk','slain',
  'slang','slant','slap','slash','slat','slaw','slay','slier','slime','slimy',
  'slob','slop','sloth','slur','smarmy','sneaky','snide','snobby','snowy','snuffy',
  'soggy','somber','soppy','soupy','spank','spawn','spear','speck','spew','spiky',
  'splay','splat','spoof','spool','spore','spout','sprout','spud','spunk','spurn',
  'spurt','squab','squat','stab','staid','stash','stein','steno','stoic','stony',
  'stoat','stout','strut','sudsy','sulky','sullen','surly','swipe','swoop','taint',
  'tawny','taunt','taut','taupe','tawny','teeming','terse','tithe','toady','toddy',
  'tommy','toper','topsy','torso','touchy','tuber','tumid','turbo','turgid','tushy',
  'tuxedo','twang','tweak','tweed','tweet','twixt','udder','ulcer','uncap','uncut',
  'unfit','ungag','unhip','union','unpin','unrip','untie','unzip','vague','vapid',
  'vaunt','vexed','viand','viper','vying','wacky','wager','waltz','warty','wavy',
  'wedge','weedy','whelp','wimpy','windy','wispy','witty','wooly','wormy','woozy',
  'wrath','wrung','yawning','zippy',
];

const ADDITIONAL_VALID = [
  // Common nouns
  'horse','rooms','doors','towns','goals','girls','kings','wings','rings',
  'funds','bonds','banks','boats','coats','cards','yards','bards','birds',
  'herds','nerds','curds','terms','germs','firms','worms','norms','dorms',
  'desks','risks','disks','tasks','masks','tusks','pools','tools','fools',
  'reeds','seeds','weeds','hours','tours','fours','looms','booms','zooms',
  'combs','bombs','curls','hurls','earls','burls','grids','bikes','parks',
  'farms','hills','balls','walls','halls','falls','beads','knees','trees',
  'songs','words','lines','names','games','times','dates','boxes','lakes',
  // Common verb forms
  'gives','takes','shows','tells','heads','hands','backs','turns','parts',
  'calls','reads','feels','leads','makes','bakes','cakes','fakes','rakes',
  'wakes','hikes','likes','faces','races','laces','paces','bases','cases',
  'tames','dames','limes','mimes','dimes','gates','fates','hates','mates',
  'rates','mites','bites','kites','sites','cites','notes','votes','totes',
  'hopes','ropes','copes','bones','tones','zones','cones','hones','homes',
  'domes','tubes','cubes','lobes','vibes','tides','rides','hides','sides',
  'codes','nodes','modes','dries','fries','loves','doves','coves','roves',
  'moves','caves','raves','paves','saves','waves','bores','cores','pores',
  'sores','cures','lures','fuses','muses','buses','roses','poses','noses',
  'hoses','doses','vases','fares','cares','dares','hares','mares','bares',
  'wares','wires','tires','hires','fires',
  // Past tense forms
  'loved','moved','roved','caved','raved','paved','saved','waved','named',
  'tamed','faked','baked','raked','hiked','liked','faced','raced','paced',
  'based','cased','gated','fated','hated','mated','rated','dated','coded',
  'domed','homed','tubed','cubed','tided','sided','dazed','fazed','gazed',
  'hazed','razed','toted','noted','voted','doted','roped','doped','moped',
  'coped','hoped','honed','toned','zoned','boned',
  // Plural/other
  'bills','fills','kills','mills','pills','sills','tills','wills','polls',
  'rolls','tolls','dolls','pulls','burns','earns','ferns','moors','longs',
  'bongs','gongs','tongs','cords','lords','ponds','wands','bands','lands',
  'sands','tweed','gusts','busts','dusts','musts','rusts','taxis','deals',
  'meals','seals','heals','peals','reals','spies','skies','cries','flies',
  'tries','hired','tired','fired','wired','mired','fined','lined','mined',
  'pined','dined','wines','dines','mines','fines','pines','vines','eaves',
];

export const VALID_GUESSES = new Set([...ANSWER_WORDS, ...EXTRA_VALID, ...ADDITIONAL_VALID]);

// ─── Public API ─────────────────────────────────────────────────────────────

export function getDailyWord(mode = 'normal') {
  const seed = getTodaySeed();
  const rand = seededRandom(seed + mode);
  const idx  = Math.floor(rand() * ANSWER_WORDS.length);
  return ANSWER_WORDS[idx].toUpperCase();
}

export function getRandomWord(mode = 'normal') {
  const idx = Math.floor(Math.random() * ANSWER_WORDS.length);
  return ANSWER_WORDS[idx].toUpperCase();
}

export function isValidWord(word, _mode = 'normal') {
  return VALID_GUESSES.has(word.toLowerCase());
}

export function getWordLength(_mode = 'normal') {
  return 5;
}
