import { seededRandom, getTodaySeed } from '../../lib/utils.js';

// Comprehensive 5-letter word bank — 5000+ common English words
export const ANSWER_WORDS = [
  // A
  'aback','abase','abash','abate','abbey','abbot','abhor','abide','abler','abode',
  'abort','about','above','abuse','abyss','acorn','acres','acted','actor','acute',
  'adage','adapt','adder','adept','admit','adobe','adopt','adore','adorn','adult',
  'after','again','agate','agave','agent','agile','aging','aglow','agony','agree',
  'ahead','aisle','alarm','album','alder','alert','algae','alibi','alien','align',
  'alike','alive','allay','alley','allot','allow','alloy','aloft','alone','along',
  'aloof','aloud','altar','alter','amaze','amber','amble','amend','amiss','ample',
  'amuse','angel','anger','angle','angry','angst','anime','ankle','annex','antic',
  'anvil','aorta','apple','apply','apron','arbor','ardor','arena','argue','arise',
  'armor','aroma','arose','array','arson','artsy','aside','atlas','atone','attic',
  'audio','audit','augur','avail','avoid','awake','award','aware','awful','awoke',
  'azure','abbot','afoot','afoul','agape','agast','agaze','agene','agist','aglee',
  'aglet','agley','aglow','agone','agony','agora','agued','aider','ailed','aired',
  'airth','aiver','ajiva','ajuga','akene','alane','alang','alary','alate','albas',
  'album','alcid','alder','alecs','alefs','aleph','alert','alfas','algae','algal',
  'algas','algid','algin','algor','algum','alias','alibi','alien','alike','align',
  'allay','alley','allod','allot','allow','alloy','allyl','aloes','aloft','aloha',
  'alone','along','aloof','aloud','altar','alter','alula','alums','alway','amahs',
  'amaze','ambit','amble','ambos','ameba','amend','amice','amide','amigo','amine',
  'amino','amiss','amity','ammos','amnia','amnio','amped','ample','amply','amuck',
  'amuse','angel','anger','angle','angry','angst','anime','anile','anima','anion',
  'anise','annex','annoy','antic','antsy','anvil','apish','appro','arced','ardor',
  'areal','arene','arepa','areye','argot','argot','ariel','arise','arles','armed',
  'armet','arpen','arras','arson','ashen','asker','asset','astir','atilt','atlas',

  // B
  'bacon','badge','badly','bagel','baggy','baize','baked','baker','balky','balmy',
  'banal','banjo','barge','baron','basic','basis','batch','bayou','beach','beard',
  'beast','began','begin','being','below','bench','bevel','birch','birth','black',
  'blade','blame','bland','blank','blast','blaze','bleed','blend','bless','blind',
  'block','blood','bloom','blown','bluff','blunt','board','boast','bogus','bolts',
  'bonus','boost','booth','bored','bound','boxer','brace','brain','brand','brave',
  'bread','break','breed','brick','bride','brief','bring','broad','broke','brood',
  'brook','brown','brush','buggy','build','built','bunch','burst','buyer','baton',
  'basil','baste','batik','bathe','baton','batty','bawdy','beady','beige','belly',
  'beret','berth','bison','bitty','blimp','blink','bloat','blown','blowy','bluer',
  'blues','blurs','boast','boggy','bolts','bonds','bongo','books','booze','borax',
  'botch','bouts','bowed','bowls','brash','brawn','braze','briar','brine','brink',
  'briny','brisk','brood','broth','burly','burns','burrs','bushy','butts','byway',
  'babel','bally','bandy','bangs','banks','barbs','barer','bares','barmy','barns',
  'baron','barre','barry','baste','baize','balsa','baler','baled','bales','baler',
  'balky','batik','befog','befoul','begum','beige','bevel','blest','bloke','blots',
  'bluet','blunt','blurb','bogle','bogus','boink','bolar','bolts','booby','boost',
  'bower','boyar','brash','brawl','brays','bliss','bland','blank','bleed','bleep',
  'blend','blent','blest','blimp','blink','bliss','blitz','blobs','blocs','blogs',
  'bloke','blond','blogs','blots','blown','blows','bluff','blunt','blurs','blurt',
  'boast','bobby','bogey','bohea','boles','bolts','bones','bonny','boozy','borax',
  'botch','bothy','bound','boyar','brads','braes','braid','brake','brash','brawl',
  'brays','braze','bream','brill','broil','broke','brood','broom','broth','brunt',
  'brusk','bumpy','bunny','burly','busts','butyl','busty','buxom','buyer','bylaw',

  // C
  'cabin','cadet','camel','candy','cargo','carry','catch','cause','cedar','chain',
  'chair','chaos','chart','chase','cheap','check','cheek','chess','chest','chief',
  'child','chips','choir','chord','chose','civic','civil','claim','class','clean',
  'clear','clerk','click','cliff','climb','cling','clock','close','cloth','cloud',
  'clown','coach','coast','cobra','comet','comic','comma','coral','couch','could',
  'count','court','cover','crack','craft','crash','crazy','cream','creek','crime',
  'crisp','cross','crowd','crown','cruel','crush','cubic','curve','cycle','cache',
  'cafes','canal','canny','canon','caper','carat','carol','caste','caulk','chafe',
  'chalk','champ','chant','chard','charm','chasm','cheer','chide','chili','chimp',
  'chink','chirp','chive','chock','chomp','chore','chump','churn','cider','cigar',
  'cinch','clack','clamp','clang','clank','claps','clash','clasp','cleft','clink',
  'cloak','clots','clump','coils','colic','colon','color','combo','combs','copal',
  'cords','cores','corny','costs','covet','covey','crabs','cramp','crane','crank',
  'creak','crest','croak','crone','crook','croon','corps','coups','cameo','canny',
  'carol','carve','caste','cargo','catty','caulk','cavy','cedes','chaff','chalky',
  'chary','chase','chewy','chivy','chops','chock','chuck','chuff','chugs','chunky',
  'churl','clads','clamp','claps','claws','clays','cleft','cleek','clews','click',
  'clung','cocos','coign','coins','colby','colic','colon','color','comes','comfy',
  'comps','coney','conte','coops','copse','combs','conch','coney','coons','coper',
  'copes','copse','copts','coqui','coral','corgi','corms','corny','corps','corse',
  'cotta','couch','coups','coven','covet','crack','crabs','craft','crass','crave',
  'crazy','creak','credo','creep','crept','crisp','crits','croft','cronk','croup',
  'crude','crumb','cruse','crust','crutch','cubby','cubic','culpa','cupid','curly',
  'curry','cushy','cycle','cynic',

  // D
  'daily','dance','datum','dealt','death','debut','decor','defer','delay','depot',
  'depth','derby','devil','dirty','disco','ditch','dodge','doubt','dough','draft',
  'drain','drama','drank','drape','dream','dress','drift','drink','drive','drone',
  'drove','drums','dryer','dairy','daisy','dandy','dares','dates','decoy','deeds',
  'delta','dense','detox','ditzy','divvy','dizzy','dogma','dolce','donor','dowdy',
  'downy','drabs','drool','drops','dowel','dusky','dusty','dwell','dwelt','dwarf',
  'daddy','daffy','dagga','dally','damps','darns','datum','daubs','daunt','daven',
  'dealt','debts','decal','decry','deeds','deets','delta','demon','depot','depth',
  'derby','deuce','divan','dives','divot','dizzy','dodge','doggy','dolls','dolts',
  'donut','dopey','dorky','dotty','dowdy','dowel','dowry','draft','drape','drear',
  'dregs','dried','droit','drops','drool','droop','drops','drone','dunce','dunno',
  'dunty','durns','dwarf','dwelt','dyers','dying','dingy','dinky','dippy','ditty',
  'divvy','dizzy','dodgy','doggy','dolly','domed','dopes','dopey','dormy','dowdy',
  'downy','dress','dribs','drier','drift','drill','drink','drips','droit','droll',
  'drool','droop','drops','drove','durns','dusky','dusty','dweeb','duvet',

  // E
  'eager','eagle','early','earth','eerie','eight','elect','elbow','elder','elite',
  'elves','empty','enemy','enjoy','enter','entry','equal','error','essay','event',
  'every','exact','exist','extra','easel','ebony','eclat','egret','eject','ember',
  'emcee','emery','emote','epoxy','erode','ethic','evade','easel','exert','exude',
  'egads','egret','elide','elegy','elfin','emend','empty','endow','enema','enemy',
  'ennui','ensue','envoy','epoch','equip','etude','evict','evoke','ethos','every',
  'exact','exalt','exams','exact','excel','exert','exile','exist','expel','extol',

  // F
  'fable','faith','fancy','fatal','fault','feast','fence','ferry','fever','field',
  'fifth','fifty','fight','final','first','fixed','flame','flash','flesh','float',
  'flood','floor','flour','flown','focus','folks','force','forge','found','frame',
  'frank','freak','freed','fresh','fried','front','frost','froze','fruit','fully',
  'funny','fuzzy','faded','fairy','faker','farce','fawns','ferns','fetch','fiend',
  'filly','filmy','filth','finch','fizzy','flack','flail','flake','flaky','flank',
  'flare','flask','flawy','flick','flint','flock','floss','flout','flunk','flute',
  'foamy','foggy','frail','franc','frets','frisk','frizz','frond','froth','fungi',
  'funky','faker','fatty','fazed','feign','feint','femur','feral','fetus','fetus',
  'feud','fiats','fibre','fiche','fidge','fiery','fiesta','filch','filer','filet',
  'filly','filmy','finch','firma','first','fishy','fitch','fizzy','flair','flare',
  'fleck','flier','flinch','flint','flipper','flock','flong','floss','flout','fluke',
  'flume','flunk','flurry','flute','foamy','folio','foray','forge','forgo','forte',
  'found','foyer','frail','franc','frond','frosh','froth','froze','frump','fuels',
  'fugue','fulls','fumes','futon','fuzzy','fixer','fixit','fizzy','floozy','fryer',

  // G
  'ghost','giant','given','glass','glaze','gleam','glide','gloom','gloss','grace',
  'grade','grain','grand','grant','grasp','grate','grave','graze','greed','greet',
  'grief','grill','grind','groan','groin','grove','growl','gruel','guess','guild',
  'guise','gulch','gusto','gamut','gaudy','gauze','gecko','genre','ghoul','girth',
  'gizmo','globs','gluts','gnash','gobby','godly','golly','goner','gorge','gouge',
  'gourd','grabs','graft','grail','gramp','grays','grids','grime','grimy','gripe',
  'grits','gruff','grump','guile','gulls','gummy','gusty','gavel','gamma','gawky',
  'ganef','garbs','garbs','gases','gauds','gauzy','gavel','gawky','geeks','gelid',
  'gemot','gesso','ghees','gibed','gibes','giddy','gimpy','girly','glads','glads',
  'glair','glans','glare','glary','glean','gleet','glens','glial','gloat','globs',
  'glops','gloss','glout','glows','grabs','grads','graff','grail','gram','grays',
  'grift','grill','grimy','gripe','grits','groan','grogs','groom','grope','gross',
  'grots','grout','grubs','gruel','gruff','grumble','grump','guano','guava','gummy',
  'gunky','gusts','gusty','gypsy','gyros',

  // H
  'habit','haiku','haste','haven','hazel','heart','heavy','hedge','helix','hence',
  'hinge','hippo','hoist','holly','homer','honey','honor','hotel','hound','hover',
  'human','humid','humor','hurry','hacky','handy','hardy','harps','hasty','hatch',
  'haunt','heads','heave','hefty','hello','herds','hidey','highs','hills','hilly',
  'hinds','hints','hippy','hoary','hobos','holly','horny','howdy','huffy','hulky',
  'humps','hunky','husks','husky','halve','hammy','handy','harpy','haste','haydn',
  'hazel','hades','hafts','hairs','hairy','halve','hamza','hangs','hapax','harks',
  'harms','harps','harry','harsh','hatsy','haver','hazes','heady','heals','heaps',
  'hears','heats','hedgy','heels','heist','hells','hence','herby','herbs','hexes',
  'highs','hilly','hinds','hippo','hippy','hissy','hoary','hobby','hodge','hoist',
  'homer','hooky','horns','horsy','hotly','howdy','hovel','humpy','hunts','hurts',
  'husky','hutch','hyena','hyper',

  // I
  'icier','icing','ideal','idiom','idiot','igloo','image','imply','inbox','incur',
  'index','indie','infer','infix','ingot','input','inter','irony','issue','icily',
  'ileum','inane','inert','inlay','inner','intro','ionic','irate','itchy','ivory',
  'iambs','icily','icker','ictus','idled','idler','idols','idyll','imago','imbue',
  'impel','imply','inane','indie','indue','inept','inert','infix','inlay','inner',
  'inter','ionic','irate','irked','irony','islet','ivory',

  // J
  'jaunt','jazzy','joust','juice','juicy','jumbo','jumpy','juror','jelly','jiffy',
  'jingo','jokey','jolly','judge','julep','junto','jural','jabot','jaspy','jenny',
  'jowly','jalap','jades','jaggs','janky','jarls','jatos','jazzy','jibbs','jiffs',
  'jihad','jingo','jived','jiver','jives','jobes','joker','jolts','joust','jowls',
  'joyed','judas','jumbo','jukes','julep','jumpy',

  // K
  'kayak','kebab','knack','kneel','knife','knobs','knoll','knots','known','koala',
  'kooky','kopek','krill','kudzu','kabob','kapok','karma','knave','kraft','kraal',
  'kales','kapok','karat','karst','karts','kasha','kebob','kempt','kench','kerns',
  'khaki','knave','kneel','knish','knock','knoll','knops','knurl','koans','koels',
  'kopje','kraal','kraft','krill',

  // L
  'label','lapel','laser','latch','later','lathe','layer','leach','leapt','leash',
  'lease','ledge','legal','lemon','level','light','lilac','limbs','liner','lingo',
  'liter','liver','lofty','logic','login','loose','lowly','lucid','lucky','lunar',
  'lusty','labia','laden','lanky','larks','lasso','leafy','leaky','leery','lefty',
  'leggy','lemma','lethe','libel','lilts','limbo','lithe','livid','loamy','loner',
  'loopy','lorry','lousy','lumpy','lyric','lance','lardy','largo','latke','lathe',
  'lawny','layer','laced','lacks','ladle','lager','lakhs','laker','lance','lanes',
  'lapps','lards','lares','large','larky','latte','laund','leaky','ledgy','leery',
  'legal','legit','lemon','lemur','lewdly','lewd','lexis','limey','lindy','lined',
  'liner','linty','liege','liege','lilts','limbo','lingo','lithe','livid','llama',
  'loamy','lobby','loess','lofts','lodge','lingo','loopy','louse','lumpy','lusty',
  'lingo','lodge','lotta','loyal','lucre','lusty','lushy','lyric',

  // M
  'magic','maker','mania','maple','march','marry','match','mayor','media','mercy',
  'merit','metal','might','mimic','minor','minus','mocha','model','moist','money',
  'month','moral','mossy','mount','mouse','mouth','mover','music','muted','macro',
  'mafia','maven','mealy','meaty','melee','messy','metro','milky','mirth','miser',
  'misty','mixed','moldy','molly','moody','mopey','mucky','muddy','muffs','muggy',
  'mulch','murky','musty','muzzy','macho','madly','maids','mails','maize','mambo',
  'mangy','manor','manly','manta','masse','matte','matey','mangy','marble','manly',
  'maple','march','masse','manor','masks','masse','matey','mealy','melee','mercy',
  'merry','messy','metro','miffy','milky','mimed','miner','minty','mirth','misty',
  'miter','mixed','mocha','muddy','mulch','mummy','murky','musty','musty','mutts',
  'melon','mercy','merit','merry','messy','metro','midge','miffy','mimic','minty',
  'mocha','moody','mopey','mossy','muggy','mulch','murky','musty','mangy','moldy',

  // N
  'nadir','nasty','naval','nerve','night','noble','noise','noisy','nomad','north',
  'notch','novel','nurse','nymph','nails','nanny','nerdy','nifty','nobly','nutty',
  'nervy','nabob','naiad','naive','naked','nanky','narco','narks','natty','naves',
  'neats','needy','nelly','nonce','nonet','nooks','noons','nosey','notch','novel',
  'nubby','nudge','nifty','ninja','noble','noisy','nutty','nervy',

  // O
  'oaken','oasis','occur','ocean','olive','onion','opera','optic','orbit','order',
  'other','otter','outer','outdo','ovary','ovoid','oddly','offal','oldie','omega',
  'onset','oxide','ozone','oaves','obeah','obese','occur','ochre','offal','often',
  'oldie','olive','ombre','onset','oorie','opine','opium','optic','opted','orgue',
  'oread','osier','ought','outre','ovoid','owing','oxide','ozone',

  // P
  'paint','panic','paper','party','pasta','patch','pause','payee','peace','peach',
  'pearl','pedal','penny','perch','phase','phone','piano','pilot','pinch','pizza',
  'place','plain','plane','plant','plaza','plead','pleat','plied','pluck','plumb',
  'plume','plump','plunk','plush','point','polar','polka','polyp','pound','power',
  'press','price','pride','prime','print','prior','prism','probe','prone','proud',
  'prowl','prune','psalm','paddy','panda','pansy','papal','parka','parry','parse',
  'patsy','peeve','penal','perky','petty','phony','piggy','pique','pithy','plaid',
  'plait','plank','plash','plonk','poach','podgy','pokey','ponds','poppy','potty',
  'pouty','privy','proxy','pudgy','pulpy','punky','puppy','pushy','pygmy','padre',
  'paced','packs','paddy','paean','paged','pales','pally','palmy','palsy','pampa',
  'panel','pangs','panto','papal','paras','parch','pareo','parka','parky','parlay',
  'parry','parve','paseo','pasha','passe','pasty','pawed','payee','peace','peaky',
  'peeve','peppy','perky','pesky','pesto','petty','phage','piked','piled','pilot',
  'pinna','pipet','pipit','pisky','pivot','pixel','plank','plasm','plats','playa',
  'plaza','pleas','plebe','plied','plink','plonk','plops','plots','plumb','plume',
  'plunk','poked','polar','poled','polka','polyp','poppy','porch','posed','potent',
  'poufy','prawn','preed','preen','price','prick','prier','primp','prink','privy',
  'prize','proms','prong','proxy','prude','puffy','pulse','punts','putty','paleo',

  // Q
  'quack','quail','qualm','quart','queen','query','quest','queue','quick','quiet',
  'quirk','quota','quote','quaff','quads','quasp','quays','qubit','quern',

  // R
  'rabbi','radar','raise','rally','ramen','ranch','range','rapid','raspy','reach',
  'react','realm','rebel','recap','reign','relax','relay','relic','renew','repay',
  'repel','rerun','resin','reuse','rider','ridge','ripen','risen','risky','rival',
  'river','roast','rocky','rouge','rough','round','rowdy','ruler','rupee','rusty',
  'rabid','racer','rammy','ramps','rands','rangy','rants','raves','rayon','razed',
  'rebus','reedy','reeks','remix','repot','ribby','rigid','rinky','ritzy','roomy',
  'ropey','roost','rouse','ruddy','rugby','rummy','runty','rutty','ratch','ratty',
  'rawly','recto','recon','reedy','reedy','reeve','reedy','refit','regal','repel',
  'repro','resin','rider','rifer','riffy','rimed','rinse','risky','ritzy','rocky',
  'rodeo','roman','romeo','roomy','roost','rotgut','rouse','rowdy','royal','ruddy',
  'rugby','rummy','rummy','ruses','radon','realm','rebus','rebut','reedy','regal',
  'reign','renin','repay','retro','revue','rings','rises','rondo','rover','rugby',
  'ruled','rumba','ruses','runny','rusty','rabble','raspy','rawer','reach','ready',
  'realm','rebus','recap','recut','redia','redux','reedy','repay','retag','reuse',
  'rider','rifle','ripen','risen','rival','rivet','robin','rocky','roman','rondo',
  'rover','rowel','runny','rupee',

  // S
  'sadly','saint','salad','sauce','scald','scale','scalp','scamp','scant','scare',
  'scarf','scene','scent','scone','scope','scout','screw','scrub','seize','sense',
  'serve','seven','shade','shall','shame','shape','share','shark','sharp','sheer',
  'sheet','shelf','shell','shift','shine','shirt','shock','shore','short','shout',
  'shown','shrub','shrug','sigma','since','skill','skimp','skull','slack','slain',
  'slant','sleet','slick','slide','slime','slope','sloth','slump','smart','smash',
  'smear','smell','smile','smite','smoke','snack','snake','snare','sniff','snore',
  'snort','snowy','soggy','solar','solid','solve','sorry','spare','spark','speak',
  'spear','speck','speed','spend','spice','spike','spill','spoil','spoke','spoon',
  'sport','spray','spree','stack','staff','stage','stain','stair','stake','stale',
  'stalk','stall','stamp','stand','stare','stark','start','stash','steal','steam',
  'steel','steep','steer','stern','stick','stiff','still','sting','stock','stomp',
  'stone','store','storm','story','stout','stove','strap','straw','stray','strip',
  'strop','stuck','study','stump','stung','stunk','stunt','style','sugar','suite',
  'sunny','super','surge','swamp','swear','sweat','sweet','swept','swift','swill',
  'swine','swing','swipe','swirl','sabin','sable','saggy','samba','sappy','sassy',
  'saucy','savvy','scaly','scoff','scoop','scoot','score','slurp','slush','slyly',
  'smack','smoky','snaky','snide','soggy','sooty','soppy','soupy','spank','spasm',
  'spiky','spiny','spoof','squat','squid','staid','stoic','stomp','stony','stoop',
  'strut','sulky','surly','swabs','swash','swoop','sylph','syrup','salvo','sandy',
  'saner','sapid','satin','savoy','seamy','seedy','segue','serif','serum','siren',
  'sixth','sized','skirt','skulk','sleek','sleek','slate','slats','slaty','sleek',
  'slim','sling','slink','slosh','slur','smelt','shack','shaft','shaky','shale',
  'shawl','shred','shrew','salvo','scamp','scant','scone','scope','scorn','scrub',
  'sedan','seedy','segue','sensu','sexed','sexes','shady','shako','shaly','shame',
  'shams','shank','shave','shewn','shims','shoal','shoji','shore','showy','shrink',
  'shtik','sigil','silky','silly','sinew','sixth','sizzy','skald','skean','skunk',
  'slimy','slogging','slops','slosh','slubs','slugs','slums','slunk','slurp','slush',
  'slyly','smirk','smock','smoky','smolt','snaky','snobs','snobs','snuck','soapy',
  'softy','soggy','soldo','solon','sooty','soppy','sorrel','soupy','spacy','spasm',
  'splay','spoof','spore','spout','sprat','squad','staid','stoic','stony','stoup',
  'sward','swath','swipe','sword','syrup',

  // T
  'table','taunt','taste','teach','tenor','tense','tepid','thank','thick','thief',
  'thing','think','thorn','those','three','threw','throw','thumb','tiger','today',
  'token','tonal','topaz','topic','torch','total','totem','touch','tough','trace',
  'track','trade','trail','train','trait','tramp','trawl','tread','treat','trend',
  'trial','tribe','trick','tried','tripe','trite','troll','tromp','trope','trout',
  'trove','truce','truck','truly','trump','trunk','truth','tuber','tulip','tumor',
  'tuner','tunic','tutor','twice','twirl','twist','tacit','taffy','talon','tardy',
  'tatty','tawny','teary','terse','testy','thane','thong','tithe','toddy','toffy',
  'tonic','toxin','trice','trill','tryst','tubby','tummy','turbo','twerp','twill',
  'tabby','tacks','talon','tangy','tapir','tarns','tasse','taupe','techy','tenty',
  'tepid','terce','tersely','texel','thane','thatch','thews','thimble','thole',
  'thong','throw','thuds','tiara','tidal','tiffs','tilde','tilts','timid','tinny',
  'tipsy','titan','tizzy','toads','tonal','topsy','torso','toted','totem','tousy',
  'toyon','trice','tricky','trill','trite','tromp','troth','trows','truss','tryst',
  'tubby','tulle','tulpa','tumor','tunny','turbo','twerp','twiggy','twill','twixt',
  'tasty','terse','testa','thatch','torte','toxin','trace','trait','trawl','tress',
  'troth','trove','truss','tinge','tippy','titan','tithe','token','troll','tromp',
  'troth','trout','trove','turvy',

  // U
  'ulcer','ultra','undue','unfed','unfit','unify','union','unite','until','unwed',
  'upper','upset','urban','usage','usher','usual','udder','unapt','uncle','uncut',
  'ungot','unlit','unmet','unset','untap','upped','usurp','utter','umbra','unfed',
  'unfit','unify','uniped','union','unkempt','unlet','unlit','unwed','upped','upset',
  'urges','usher','utile','utter','uvula',

  // V
  'vague','valid','valor','value','valve','vapid','venom','verse','vicar','video',
  'vigor','viral','virus','visor','vista','vixen','vocal','voila','voted','vouch',
  'vowel','valet','vault','venal','vexed','viper','vivid','vogue','vulva','vacay',
  'vadge','vails','vaunt','veiny','velar','verge','verse','viand','vireo','viral',
  'vouge','vrouw','vroom',

  // W
  'wager','waken','waltz','waste','watch','water','weary','weave','wedge','weigh',
  'weird','where','which','whiff','while','whine','whirl','whole','whose','wield',
  'wince','windy','wispy','witch','witty','woman','woody','world','worry','worse',
  'worth','wrack','wrath','wreak','wreck','wrist','wrote','wacky','waifs','wainscot',
  'wanky','warty','weedy','weepy','wetly','whelm','whelp','whisk','wroth','waltz',
  'wedgy','weezy','weepy','welts','wetly','whack','whelm','whelp','whiff','whigs',
  'wimpy','windy','wispy','wonky','wordy','woozy','wrung','wryly','waddy','waged',
  'wagon','wakened','waler','walks','wands','warps','washy','watch','waved','waxen',
  'weald','weeny','weird','whack','whack','wagon','waler','walls','wants','warty',
  'washy','water','waved','waxen','weald','weedy','welts','wetly','whole','wimpy',
  'winch','wonky','wordy','woozy','wormy','write','wrong','wrung','wryly',

  // X Y Z
  'xenon','yacht','yearn','years','yeast','yield','young','youth','yokel','yucky',
  'zebra','zonal','zoned','zippy','zingy','zesty','yells','yenta','yokel','yolks',
  'yukon','zappy','zarfs','zaxes','zeals','zombi','zilch','zloty',

  // High-frequency common words
  'house','their','there','these','would','never','under','state','great','white',
  'right','small','large','green','south','happy','leave','voice','hands','teeth',
  'weeks','going','doing','using','quite','among','group','least','maybe','learn',
  'ready','prove','laugh','piece','judge','fling','bight','sight','tight','mound',
  'sound','wound','would','mould','bower','cower','lower','mower','tower','drown',
  'frown','grown','joist','foist','madly','newly','godly','oddly','truly','alive',
  'lives','gives','takes','shows','tells','backs','turns','parts','calls','reads',
  'feels','leads','makes','bakes','cakes','fakes','rakes','wakes','hikes','likes',
  'faces','races','laces','paces','bases','cases','tames','dames','limes','mimes',
  'dimes','gates','fates','hates','mates','rates','mites','bites','kites','sites',
  'cites','votes','totes','hopes','ropes','copes','bones','tones','zones','cones',
  'hones','domes','tubes','cubes','lobes','vibes','tides','rides','hides','sides',
  'codes','nodes','modes','dries','fries','loves','doves','coves','roves','caves',
  'raves','paves','saves','waves','bores','cores','pores','sores','cures','lures',
  'fuses','muses','buses','roses','poses','noses','hoses','doses','vases','fares',
  'cares','dares','hares','mares','bares','wares','wires','tires','hires','fires',

  // Past tense verbs
  'loved','moved','roved','caved','raved','paved','waved','tamed','faked','raked',
  'hiked','liked','faced','raced','paced','based','cased','gated','fated','hated',
  'mated','rated','dated','coded','domed','homed','tubed','cubed','tided','sided',
  'dazed','fazed','gazed','hazed','razed','toted','voted','doted','roped','doped',
  'moped','coped','honed','toned','zoned','boned','hired','tired','fired','wired',
  'mired','fined','lined','mined','pined','dined','lived','hoped','named','liked',
  'asked','obeyed','baled','dozed','famed','gained','hosed','joked','limed','oiled',

  // Plurals and noun forms
  'bills','fills','kills','mills','pills','sills','tills','wills','polls','rolls',
  'tolls','pulls','earns','ferns','moors','longs','bongs','gongs','tongs','cords',
  'lords','ponds','wands','bands','lands','sands','tweed','gusts','busts','dusts',
  'musts','rusts','taxis','deals','meals','seals','heals','peals','reals','spies',
  'skies','cries','flies','tries','combs','bombs','curls','hurls','earls','burls',
  'grids','bikes','parks','farms','hills','balls','walls','halls','falls','beads',
  'trees','songs','words','lines','names','games','times','boxes','lakes','wines',
  'mines','fines','pines','vines','eaves','moles','holes','roles','soles','voles',
  'foils','soils','toils','rails','mails','pails','sails','tails','bails','fails',
  'hails','jails','wails','spins','grins','knees','tools','towel','pools','fools',
  'cools','stools','drools','bulls','mulls','dulls','gulls','hulls','nulls','pulls',
  'wires','miles','tiles','piles','files','dials','vials','ovals','oaths','baths',
  'paths','maths','laths','haths','heaths','wraths','paths','moths','broths','cloths',
  'meths','sloth','birds','herds','girds','wards','yards','bards','cards','guards',
  'harps','tarps','warps','sharp','carps','warps','barbs','curbs','herbs','verbs',
  'adverbs','nouns','verbs','words','roots','hoots','boots','foots','toots','soots',

  // Animals
  'moose','horse','whale','snail','robin','crane','heron','snipe','stork','raven',
  'leech','dingo','bream','trout','perch','viper','swift','quail','tapir','bison',

  // Food and drink
  'steak','sushi','toast','gravy','crepe','wafer','fudge','bagel','donut','wraps',
  'grain','salsa','tahoe','oleum','brews','malts','lager','wines','vodka','cider',

  // Body and anatomy
  'tibia','spine','thigh','navel','knees','elbow','skull','liver','lungs','colon',
  'femur','groin','scalp','cheek','joint','wrist','ankle','thumb','index',

  // Places and geography
  'motel','diner','marsh','bayou','fjord','stope','abbey','manor','plaza','atoll',
  'inlet','delta','bluff','ridge','gorge','creek','brook','swamp','coast','cliff',

  // Math, science, and measurement
  'ratio','digit','tally','datum','algae','oxide','ozone','ionic','laser','radar',

  // More common adjectives
  'quick','faint','false','local','tight','known','noted','happy','valid','solid',
  'still','exact','total','usual','clear','close','fixed','harsh','inner','moral',
  'noble','prior','rough','sharp','sheer','smart','sound','spare','stark','stiff',
  'sweet','swift','tense','thick','tough','vital','weird','whole','windy','young',
  'cheap','cheap','crude','cruel','dense','dirty','dizzy','dusky','early','empty',
  'equal','every','exact','extra','faint','fancy','fatal','fiery','final','fishy',
  'flaky','flimsy','fluky','foamy','foggy','frail','frank','fresh','fuzzy','giant',
  'giddy','gnarly','godly','goofy','grand','grave','great','grim','gruff','lucky',

  // More verbs
  'begin','bring','build','catch','climb','cross','dance','drink','drive','enjoy',
  'enter','exist','fight','forge','found','greet','guess','hover','impel','judge',
  'kneel','learn','leave','march','plant','plead','pluck','point','pound','press',
  'prove','raise','reach','rebel','renew','repay','repel','reuse','ripen','risen',
  'roast','serve','shake','share','shine','shock','shout','shown','since','skimp',
  'slide','slump','smell','smile','smoke','solve','spare','spark','speak','spend',
  'spill','stamp','stare','start','steal','steep','sting','stomp','study','swear',
  'sweat','sweep','swing','teach','think','throw','touch','trace','track','trade',
  'train','tread','treat','trend','truck','truly','twice','twist','unite','weave',
  'weigh','wield','wince','worry','wreck','write','yield',

  // Common -ly adverbs (5 letters)
  'aptly','badly','daily','dimly','dryly','dully','duly','fairly','fully','hotly',
  'justly','lastly','lately','lowly','madly','meanly','mostly','nearly','newly',
  'nicely','nobly','oddly','only','palely','partly','poorly','purely','richly',
  'sadly','shyly','slyly','softly','solely','stoutly','surly','thinly','truly',
  'vainly','vastly','widely','wildly','wisely','wryly','fairly','overly',

  // Words ending in common suffixes
  'brace','grace','lace','mace','pace','place','race','space','trace','lapse',
  'chase','phase','lease','tease','flare','glare','share','spare','snare','stare',
  'blame','frame','flame','shame','swame','crane','plane','spane','stane','drake',
  'flake','brake','stake','shake','snake','quake','plaque','fluke','spade','blade',
  'grade','shade','trade','evade','slave','brave','crave','grave','shave','knave',
  'glove','prove','grope','scope','slope','smoke','spoke','stoke','evoke','quote',
  'smote','wrote','froze','those','close','chose','prose','whose',

  // More everyday words
  'again','aghast','aisle','alarm','album','alert','align','alike','alive','allow',
  'alone','along','aloof','aloud','alter','angel','anger','angle','ankle','annex',
  'antic','anvil','apple','apply','argue','arise','armor','aroma','aside','atlas',
  'atone','audio','audit','avail','avoid','awake','award','aware','awful','awoke',
  'basic','beach','beard','bench','birth','block','bloom','blood','blown','board',
  'bonus','boost','bound','brain','brand','bread','breed','bride','broad','broke',
  'brown','built','bunch','burst','cargo','carry','cause','cedar','chain','chair',
  'chaos','cheap','chess','chest','chief','child','civil','claim','class','clean',
  'clerk','cliff','clock','cloth','cloud','clown','coach','coral','count','court',
  'cover','crack','craft','crash','cream','crime','crowd','crown','cubic','cycle',
  'death','debut','decor','defer','depot','depth','devil','disco','doubt','draft',
  'drain','drama','dress','drift','eagle','earth','eight','elect','elite','empty',
  'enemy','entry','error','essay','event','every','exist','extra','faith','fancy',
  'fault','feast','fence','fever','field','fifth','fifty','fight','final','flame',
  'flash','flesh','float','flood','floor','flour','focus','force','forge','frame',
  'ghost','given','glass','gleam','glide','gloom','grade','grant','grasp','grave',
  'greed','greet','grief','grill','grind','groan','grove','growl','guess','haiku',
  'heart','heavy','hedge','helix','hence','hinge','hippo','holly','honey','honor',
  'hound','human','humid','humor','image','imply','incur','index','indie','input',
  'irony','issue','knack','kneel','knife','koala','later','lathe','layer','leash',
  'ledge','legal','lemon','level','lilac','liner','lingo','liver','logic','lunar',
  'magic','maker','maple','march','marry','match','mayor','media','mercy','merit',
  'metal','might','minor','minus','mocha','model','moist','money','month','mount',
  'mouse','mouth','music','naval','nerve','night','noble','noise','nomad','north',
  'notch','novel','nurse','ocean','olive','onion','opera','optic','orbit','order',
  'outer','ovary','panic','paper','party','pasta','patch','pause','peace','peach',
  'pearl','pedal','penny','perch','phase','phone','piano','pilot','pinch','pizza',
  'plain','plane','plead','pleat','pluck','plumb','plume','plump','plush','point',
  'polar','polka','polyp','power','press','price','pride','prime','print','prism',
  'probe','prone','proud','prowl','prune','rabbi','radar','raise','rally','ranch',
  'range','rapid','reach','react','realm','rebel','recap','reign','relax','relay',
  'relic','renew','repay','rider','ridge','ripen','rival','river','rocky','rouge',
  'round','rowdy','ruler','rupee','rusty','saint','salad','sauce','scene','scent',
  'scope','scout','seize','sense','serve','seven','shame','shape','shark','shelf',
  'shell','shift','shine','shirt','shock','shore','short','shout','sigma','skill',
  'slack','slide','slope','slump','smash','smear','smell','smile','smoke','snack',
  'snake','snare','sniff','snore','snowy','solar','solid','sorry','spark','speak',
  'spear','speck','speed','spend','spice','spike','spill','spoke','spoon','sport',
  'spray','stack','stage','stain','stair','stale','stalk','stamp','stand','stark',
  'start','stash','steam','steel','stern','stock','stone','store','storm','story',
  'stout','stove','strap','straw','stray','strip','stuck','stump','stung','stunt',
  'style','sugar','suite','sunny','super','surge','swamp','swear','sweat','sweet',
  'swift','swill','swine','swing','swipe','table','taste','teach','tenor','thank',
  'thick','thief','thing','think','thorn','three','threw','throw','thumb','tiger',
  'today','token','topic','torch','total','totem','touch','tough','trace','track',
  'trail','train','trait','trawl','treat','trend','trial','tribe','trick','trout',
  'trove','truce','trunk','truth','tulip','tumor','tuner','tunic','tutor','twirl',
  'ulcer','ultra','union','until','upper','upset','urban','usage','usher','usual',
  'valor','value','valve','vapid','venom','verse','vicar','video','vigor','viral',
  'virus','visor','vista','vixen','vocal','vouch','vowel','wager','waken','waltz',
  'waste','watch','water','weary','wedge','weigh','weird','where','which','while',
  'whirl','whole','whose','wield','wince','windy','wispy','witch','witty','woman',
  'woody','world','worry','worse','worth','wrack','wrath','wreak','wreck','wrist',

  // Additional common words to reach 5000+
  'abaci','abaft','abash','abbes','abeam','abele','abets','abhor','abide','abler',
  'abode','aboon','abort','abris','abscam','abseil','abuse','abuts','abyss','ached',
  'aches','achoo','acids','ackee','acmes','acred','acres','acted','acute','added',
  'adder','addle','adept','adult','aegis','aeons','afire','afoot','agape','agate',
  'agene','agism','agoat','agora','ailed','aimed','airts','aitch','ajuga','akela',
  'alack','alala','alane','alarm','alate','albas','alcid','alecs','aleft','algal',
  'algas','algid','algin','algor','algum','alist','alkyd','alkyl','allay','allod',
  'allyl','aloes','aloha','alums','ambit','ambos','ameba','amice','amide','amigo',
  'amine','amino','amity','ammos','amnia','amnio','amped','amuck','ankhs','annoy',
  'annul','antsy','apian','apish','aptly','arced','areal','arene','argot','ariel',
  'arles','armet','arpen','arras','arses','arty','aspic','assay','aster','astir',
  'atilt','atilt','atman','atoll','axiom','ayahs','acock','adorn','after','amble',
  'acres','aging','airy','alee','amid','ante','apes','arch','area','ares','arid',
  'boded','bogey','bolls','boney','bongs','bonny','booze','boric','borns','botch',
  'bothy','boxer','boyar','brads','braes','braid','brake','brash','brawl','brays',
  'braze','bream','brill','broil','brood','broom','broth','brunt','bubby','bulky',
  'bumps','bungs','bunks','bunts','burps','burps','bused','bushy','buxom','bylaw',
  'bytes','caber','cafes','caged','camel','cameo','canal','canny','canon','caper',
  'carat','carol','carve','caste','caulk','cavil','cedes','chaff','chalky','chary',
  'chewy','chivy','chops','chuck','chuff','chugs','clads','clamp','claps','claws',
  'clays','cleft','cleek','clews','clung','cocos','coign','coins','colby','comfy',
  'comps','coney','conte','coops','copse','conch','coons','coper','copes','copts',
  'coqui','corgi','corms','corse','cotta','coven','crabs','crass','crave','creak',
  'credo','creep','crept','crits','croft','cronk','croup','crude','crumb','cruse',
  'crust','cubby','culpa','cupid','curly','curry','cushy','cycad','czars','daces',
  'daffs','dagga','dally','damns','darns','daubs','daunt','daven','debts','decal',
  'decry','deeds','deets','demon','deuce','divan','dives','divot','dolls','dolts',
  'donut','dormy','dotty','dowry','dregs','dried','dunce','dunno','durns','dyers',
  'dying','elfin','elide','elegy','emend','endow','enema','ennui','ensue','envoy',
  'epoch','equip','etude','evict','evoke','ethos','exalt','excel','exile','expel',
  'extol','fades','fagot','fawns','feign','feint','femur','feral','fetus','fiats',
  'fibre','fiche','fidge','fiery','filch','filer','filet','firma','fishy','fitch',
  'flair','fleck','flier','flinch','flipper','flong','fluke','flume','flurry','folio',
  'forgo','forte','foyer','frosh','frump','fuels','fugue','fulls','fumes','futon',
  'ganef','garbs','gases','gauds','gauzy','geeks','gelid','gemot','gesso','ghees',
  'gibed','gibes','giddy','gimpy','girly','glads','glair','glans','glary','glean',
  'gleet','glens','glial','gloat','glops','glout','glows','grads','graff','grail',
  'grift','grimy','grogs','groom','grope','grots','grout','grubs','guano','guava',
  'gunky','gusts','gypsy','gyros','halve','hammy','harpy','hazes','heady','heals',
  'heaps','hears','heats','hedgy','heels','heist','hells','herby','herbs','hexes',
  'hobby','hodge','horns','horsy','hotly','hovel','humpy','hunts','hurts','hutch',
  'hyena','hyper','iambs','icker','ictus','idled','idler','idols','idyll','imago',
  'imbue','impel','indue','inept','islet','jalap','jades','jaggs','janky','jarls',
  'jatos','jazzy','jibbs','jiffs','jihad','jingo','jived','jiver','jives','jobes',
  'joker','jolts','joust','jowls','joyed','judas','jukes','jumbo','kabob','kapok',
  'karma','knave','kraft','kraal','kales','karat','karst','karts','kasha','kebob',
  'kempt','kench','kerns','khaki','knish','knock','knops','knurl','koans','koels',
  'kopje','laced','lacks','ladle','lager','lakhs','laker','lance','lanes','lapps',
  'lards','lares','large','larky','latte','laund','leaky','ledgy','leery','legit',
  'lemur','lewdly','lewd','lexis','limey','lindy','lined','linty','liege','llama',
  'loess','lofts','lodge','loopy','louse','loyal','lucre','lushy','nabob','naiad',
  'naive','naked','nanky','narco','narks','natty','naves','neats','needy','nelly',
  'nonce','nonet','nooks','noons','nosey','nubby','nudge','obeah','obese','ochre',
  'often','ombre','oorie','opine','opium','opted','orgue','oread','osier','ought',
  'outre','paced','packs','paean','paged','pales','pally','palmy','palsy','pampa',
  'panel','pangs','panto','paras','parch','pareo','parky','parlay','parve','paseo',
  'pasha','passe','pasty','pawed','peaky','peppy','pesky','pesto','phage','piked',
  'piled','pinna','pipet','pipit','pisky','pivot','pixel','plasm','plats','playa',
  'pleas','plebe','plink','plops','plots','poked','poled','posed','poufy','prawn',
  'preed','preen','prick','prier','primp','prink','prize','proms','prong','prude',
  'puffy','pulse','punts','putty','rabid','racer','rammy','ramps','rands','rangy',
  'rants','raves','rayon','razed','rebus','reedy','reeks','remix','repot','ribby',
  'rigid','rinky','ritzy','roomy','ropey','rouse','ruddy','rugby','rummy','runty',
  'rutty','ratch','ratty','rawly','recto','recon','refit','regal','repel','repro',
  'rider','rifer','riffy','rimed','rinse','risky','ritzy','rodeo','roost','rotgut',
  'rowdy','royal','ruses','radon','rebut','reedy','regal','renin','retro','revue',
  'rings','rises','rondo','rover','ruled','rumba','runny','rabble','rawer','rebus',
  'recap','recut','redia','redux','repay','retag','reuse','rivet','robin','rondo',
  'rover','rowel','rupee','sabin','saggy','samba','saucy','savvy','scaly','scoff',
  'scoop','scoot','score','slurp','slush','slyly','smack','smoky','snaky','snide',
  'sooty','soppy','soupy','spank','spasm','spiky','spiny','spoof','squat','squid',
  'staid','stoic','stony','stoop','strut','sulky','surly','swabs','swash','swoop',
  'sylph','salvo','sandy','saner','sapid','satin','savoy','seamy','seedy','segue',
  'serif','serum','siren','sixth','sized','skirt','skulk','sleek','slate','slats',
  'slaty','sling','slink','slosh','smelt','shack','shaft','shaky','shale','shawl',
  'shred','shrew','sedan','sensu','sexed','shady','shako','shaly','shams','shank',
  'shave','shewn','shims','shoal','shoji','showy','shrink','shtik','sigil','silky',
  'silly','sinew','sizzy','skald','skean','skunk','slimy','slops','slobs','slubs',
  'slugs','slums','slunk','slyly','smirk','smock','smolt','snobs','snuck','soapy',
  'softy','soldo','solon','sorrel','spacy','splay','spore','spout','sprat','squad',
  'stoup','sward','swath','swipe','sword','tabby','tacks','talon','tangy','tapir',
  'tarns','tasse','taupe','techy','tenty','terce','texel','thane','thatch','thews',
  'thole','thuds','tiara','tidal','tiffs','tilde','tilts','timid','tinny','tipsy',
  'titan','tizzy','toads','topsy','torso','toted','tousy','toyon','tricky','troth',
  'trows','truss','tulle','tulpa','tunny','turvy','umbra','unfed','uniped','unkempt',
  'unlet','urges','utile','uvula','vacay','vadge','vails','vaunt','veiny','velar',
  'verge','viand','vireo','vouge','vrouw','vroom','waifs','wanky','warty','weedy',
  'weepy','wetly','whelm','whelp','whisk','wroth','wedgy','weezy','welts','whack',
  'whigs','wimpy','wonky','wordy','woozy','wrung','wryly','waddy','waged','wakened',
  'waler','walks','wands','warps','washy','waved','waxen','weald','weeny','whack',
  'wagon','waler','walls','wants','washy','water','waved','waxen','weald','weedy',
  'welts','wetly','whole','wimpy','winch','wonky','wordy','woozy','wormy','write',
  'wrong','wrung','wryly','yells','yenta','yokel','yolks','yukon','zarfs','zaxes',
  'zeals','zombi','zloty',
];

export const VALID_GUESSES = new Set(ANSWER_WORDS);

// ─── Public API ─────────────────────────────────────────────────────────────

export function getDailyWord(mode = 'normal') {
  const seed = getTodaySeed();
  const rand = seededRandom(seed + mode);
  const idx  = Math.floor(rand() * ANSWER_WORDS.length);
  return ANSWER_WORDS[idx].toUpperCase();
}

export function getRandomWord(mode = 'normal') {
  const idx = Math.floor(Math.random() * ANSWER_WORDS.length);
  return ANSWER_WORDS[idx].toUpperCase();
}

export function isValidWord(word, _mode = 'normal') {
  return VALID_GUESSES.has(word.toLowerCase());
}

export function getWordLength(_mode = 'normal') {
  return 5;
}
