// Word ladder puzzles — each step changes exactly 1 letter
// All solutions manually verified: every consecutive pair differs by exactly 1 letter
export const WORD_LADDER_PUZZLES = [
  { start: 'COLD', end: 'WARM', steps: 4, solution: ['COLD','CORD','WORD','WARD','WARM'] },
  { start: 'HATE', end: 'LOVE', steps: 3, solution: ['HATE','HAVE','LAVE','LOVE'] },
  { start: 'LEAD', end: 'GOLD', steps: 3, solution: ['LEAD','LOAD','GOAD','GOLD'] },
  { start: 'HAND', end: 'FOOT', steps: 5, solution: ['HAND','BAND','BOND','FOND','FOOD','FOOT'] },
  { start: 'MINE', end: 'GOLD', steps: 4, solution: ['MINE','MIND','MILD','GILD','GOLD'] },
  { start: 'BOOK', end: 'WORD', steps: 4, solution: ['BOOK','HOOK','HOOD','WOOD','WORD'] },
  { start: 'FIRE', end: 'WINE', steps: 3, solution: ['FIRE','HIRE','WIRE','WINE'] },
  { start: 'SOFT', end: 'FAST', steps: 5, solution: ['SOFT','LOFT','LOST','COST','CAST','FAST'] },
  { start: 'DARK', end: 'FIRE', steps: 4, solution: ['DARK','DART','DARE','FARE','FIRE'] },
  { start: 'BONE', end: 'TIME', steps: 5, solution: ['BONE','BANE','LANE','LAME','LIME','TIME'] },
];

export const VALID_4_LETTER_WORDS = new Set([
  'able','acid','aged','also','area','army','away','baby','back','ball','band','bank','base','bath',
  'bear','beat','been','bell','best','bill','bird','blow','blue','boat','body','bomb','bond','bone',
  'book','boom','born','both','bulk','burn','bush','busy','call','calm','came','card','care','cart',
  'case','cash','cast','cave','cell','chat','chip','city','clad','clam','clan','clap','clay','clue',
  'coal','coat','code','coil','cold','come','cook','cool','cope','copy','cord','core','corn','cost',
  'coup','crew','crop','cure','dark','damp','dart','data','date','dawn','days','dead','deal','dear',
  'debt','deck','deed','deep','deny','desk','dial','dice','died','diet','dime','disc','dish','disk',
  'dock','dome','done','door','dose','down','draw','drip','drop','drug','drum','dual','dull','dumb',
  'dump','dunk','dust','duty','each','earn','ease','east','edge','else','emit','epic','even',
  'ever','evil','exam','face','fact','fail','fair','fall','fame','farm','fast','fate','fear',
  'feel','feet','fell','felt','file','fill','film','find','fine','fire','fish','fist','flag','flat',
  'flew','flip','flow','foam','fold','folk','fond','font','food','fool','foot','ford','fore','fork',
  'form','fort','foul','four','free','from','fuel','full','fund','gale','game','gang','gate','gave',
  'gear','geld','gene','gift','gild','girl','give','glad','glow','glue','goal','gold','gone','good',
  'gown','grab','gram','grew','grid','grim','grip','grow','gulf','gust','half','hall','halt','hand',
  'hang','hard','harm','hate','have','head','heal','heap','hear','heat','heel','help','here','hero',
  'hide','high','hill','hire','hold','hole','home','hong','hook','hood','hope','horn','hose','host',
  'hour','hull','hunt','hurt','iced','idea','idol','inch','into','iron','isle','item','jack',
  'jail','join','joke','jump','just','keen','keep','kill','kind','king','knee','knew','know','lack',
  'lake','land','lane','lard','last','late','laud','lawn','lead','lean','leap','left','lent','less',
  'liar','lick','life','lift','like','limp','line','link','list','live','load','loan','lock','loft',
  'long','look','loop','loot','lord','loss','lost','loud','love','luck','lure','lust','made','mail',
  'main','make','mall','malt','many','mark','mars','mart','mass','mate','math','maze','meal','meat',
  'meet','melt','memo','mere','mild','mile','mill','mind','mine','miss','mist','mode','mold','more',
  'most','move','much','must','nail','name','near','neck','need','next','nice','nine','node','none',
  'nook','norm','nose','note','noun','nude','oath','odds','once','only','open','oral','ours','over',
  'pace','pack','page','paid','pain','pair','pale','palm','pant','park','part','pass','past','path',
  'pave','peak','peel','pick','pile','pine','pink','pipe','plan','play','plea','plod','plot','plow',
  'plus','poem','poet','poke','pole','poll','pond','pool','poor','pope','pore','port','pose','post',
  'pour','pray','prey','prix','prod','prop','pull','pump','pure','push','race','rack','rage','raid',
  'rail','rain','rake','ramp','rank','rate','read','real','reel','reef','rent','rest','rice','rich',
  'ride','ring','riot','rise','risk','road','roam','roar','rock','rode','role','roll','roof','room',
  'root','rope','rose','rude','rule','rung','rush','rust','safe','said','sail','salt','sand','sane',
  'sang','save','scan','scar','seat','seed','seek','seem','send','ship','shoe','shop','shot',
  'show','shut','sick','side','sigh','sign','silk','sing','sink','size','skin','slim','slip','slot',
  'slow','slug','snap','snow','soak','soar','soft','soil','sold','sole','some','song','soon','sort',
  'soul','soup','sour','spin','spot','star','stay','stem','step','stir','stop','such','suit','sung',
  'sunk','sure','swim','tail','tale','talk','tall','tank','tape','task','team','tear','tell','tend',
  'tent','test','text','than','that','thee','them','then','thud','tick','tide','tidy','till','time',
  'tiny','tire','toad','told','toll','tomb','tome','took','tool','tops','tore','torn','toss','tour',
  'town','trap','tree','trim','trip','true','tube','tune','turn','twin','type','ugly','upon','used',
  'user','vain','vale','vane','vast','verb','very','vest','view','vine','void','volt','vote','wade',
  'wage','wake','walk','wall','want','ward','warm','warn','wary','wash','wave','weak','wear','weed',
  'week','well','went','were','west','what','when','whom','wide','wild','will','wind','wine','wing',
  'wire','wise','wish','with','woke','wood','wool','word','wore','work','worm','worn','wrap','yard',
  'year','yell','your','zero','zone',
  // words needed for puzzle solutions
  'lave','bane','lane','lame','lime','dare','fare','goad','hook','hood',
  // common words frequently guessed
  'bark','bore','barn','bare','bean','bend','blur','bode','bray','bale',
  'cape','cane','clay','core','cook','dale','dean','fend','flaw','flay',
  'foam','fend','gape','gale','gash','gore','gray','hare','hark','idle',
  'jest','keel','knit','lard','lark','lave','leer','lens','lode','loom',
  'lore','lout','mace','male','mane','mare','mash','mean','mend','mesh',
  'moat','mock','pane','pare','pike','pint','plum','puck','punt','rare',
  'rasp','rave','raze','rein','rend','rife','rift','rime','rink','robe',
  'rook','rout','rove','sale','seam','sear','shin','shun','slap','sled',
  'slew','slit','smug','snag','snob','snug','sore','soot','spur','stub',
  'stud','stun','surf','taut','tier','tilt','toil','tong','vale','veal',
  'veer','vend','vent','vile','wail','wale','wane','wart','wasp','weld',
  'welt','wend','whet','wile','wilt','wink','wipe','wore','wren','yarn',
  'yawn','yelp','yore','zeal','lend','rend','fend','mend','pang','loom',
  'lune','gust','sift','hike','look','rook','foes','fawn','lame','boon',
  'barn','harm','hark','park','lark','mark','darn','tarn','fare','dare',
  'hare','mare','pare','bare','care','gore','more','bore','core','lore',
  'wore','tore','sore','lime','lame','lane','bane','cane','mane','pane',
  'bean','dean','lean','mean','wean','hook','hood','look','rook','cook',
]);
